<template>
  <div class="module-theme min-h-screen bg-slate-900 text-slate-100 flex">
    <SupplierSidebar v-if="supplierView" /><OwnerSidebar v-else />
    <main class="min-w-0 flex-1 p-4 md:p-8">
      <header class="flex flex-wrap justify-between gap-4 mb-6"><div><p class="text-xs uppercase tracking-widest text-amber-300">{{ departmentLabel }}</p><h1 class="text-2xl font-bold">{{ pageTitle }}</h1><p class="mt-2 text-sm text-slate-400">{{ intro }}</p></div><div class="flex gap-2 items-start"><select v-if="!supplierView" v-model="branchId" @change="load"><option v-for="branch in data.branches" :key="branch.id" :value="branch.id">{{ branch.name }}</option></select><button @click="load" :disabled="busy">Refresh</button></div></header>
      <p v-if="error" role="alert" class="mb-4 rounded border border-red-500 bg-red-900/30 p-4">{{ error }}</p>
      <p v-if="notice" role="status" class="mb-4 rounded border border-emerald-600 p-4">{{ notice }}</p>
      <p v-if="loading">Loading department records…</p>
      <template v-else>
        <nav class="module-tabs mb-5" role="tablist" :aria-label="`${departmentLabel} sections`"><router-link v-for="tab in tabs" :key="tab.key" :to="tab.to" class="module-tab" role="tab" :aria-selected="tab.key === page" :class="{ 'module-tab-active': tab.key === page }">{{ tab.label }}</router-link></nav>
        <div v-if="page === 'dashboard'" class="space-y-5">
          <div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><article v-for="card in cards" :key="card.label" class="rounded-xl border border-slate-700 bg-slate-800 p-4"><p class="text-sm text-slate-400">{{ card.label }}</p><strong class="mt-2 block text-2xl">{{ card.value }}</strong></article></div>
          <div class="grid gap-4 md:grid-cols-2"><section v-for="chart in charts" :key="chart.title" class="rounded-xl border border-slate-700 p-5"><h2 class="mb-4 font-semibold">{{ chart.title }}</h2><div v-for="entry in chart.entries" :key="entry.label" class="mb-3"><div class="flex justify-between text-sm"><span>{{ entry.label }}</span><span>{{ chart.money ? currency(entry.value) : entry.value }}</span></div><div class="mt-1 h-2 rounded bg-slate-700"><div class="h-2 rounded bg-amber-500" :style="{ width: Math.max(2, 100 * Math.abs(entry.value) / chart.max) + '%' }"></div></div></div><p v-if="!chart.entries.length" class="text-sm text-slate-400">No data recorded yet.</p></section></div>
          <section class="rounded-xl border border-slate-700 p-5"><h2 class="font-semibold">Alerts and next actions</h2><p v-for="alert in alerts" :key="alert" class="mt-2 text-sm text-amber-200">{{ alert }}</p><p v-if="!alerts.length" class="mt-2 text-sm text-slate-400">No outstanding alerts.</p></section>
        </div>
        <template v-else>
          <div class="module-actions mb-4">
            <button v-if="page === 'items' && can('inventory:create')" class="module-action" title="Register item from supplier catalog" @click="openItem()"><span aria-hidden="true">＋</span> Register item</button>
            <button v-if="page === 'suppliers' &amp;&amp; can('suppliers:create')" class="module-action" title="Add manual supplier" @click="openForm('supplier')"><span aria-hidden="true">＋</span> Add supplier</button><router-link v-if="page === 'suppliers'" to="/procurement/suppliers/directory" class="module-action" title="Manage or invite suppliers"><span aria-hidden="true">↗</span> Supplier directory</router-link><button v-if="page === 'requests' && department === 'inventory' && can('inventory:create')" class="module-action" title="Create inventory request" @click="openForm('request')"><span aria-hidden="true">＋</span> New request</button>
            <button v-if="page === 'budgets' && can('finance:payables:approve')" class="module-action" title="Create budget" @click="openForm('budget')"><span aria-hidden="true">＋</span> Create budget</button>
            <select v-if="page === 'reports'" v-model="reportKey" aria-label="Report type"><option v-for="(r,index) in availableReports" :key="r.key" :value="index === 0 ? '' : r.key">{{ r.label }}</option></select><button class="module-action" title="Export filtered report" @click="exportCsv"><span aria-hidden="true">⇩</span> Export report</button>
          </div>
          <div class="mb-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">
            <input v-model="search" placeholder="Search name, reference, related ID" aria-label="Search records" />
            <select v-model="status"><option value="">All statuses</option><option v-for="value in statuses" :key="value">{{ value }}</option></select>
            <select v-model="type"><option value="">All record types</option><option v-for="value in types" :key="value">{{ value }}</option></select>
            <input v-model="departmentFilter" placeholder="Department" aria-label="Department filter" />
            <select v-model="supplierFilter"><option value="">All suppliers</option><option v-for="s in data.suppliers" :key="s.id" :value="s.id">{{ supplierName(s.id) }}</option></select>
            <input v-model="categoryFilter" placeholder="Category" aria-label="Category filter" />
            <label class="text-xs text-slate-400">From<input type="date" v-model="fromDate" /></label><label class="text-xs text-slate-400">Through<input type="date" v-model="toDate" /></label>
            <select v-model="sort"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Name/reference</option></select>
          </div>
          <div class="overflow-x-auto rounded-xl border border-slate-700"><table class="w-full text-left text-sm"><thead class="bg-slate-800"><tr><th>Reference / Item</th><th>Type</th><th>Status / DSS</th><th>Quantity / Amount</th><th>Next action</th><th></th></tr></thead><tbody><tr v-for="row in pagedRows" :key="row.id" class="border-t border-slate-700"><td><img v-if="row.imageUrl" :src="row.imageUrl" alt="" class="mr-2 inline-block h-10 w-10 rounded object-cover" />{{ row.number || row.name || row.businessName || row.id }}<small class="block text-slate-400">{{ row.brand || row.department || supplierName(row.supplierId) }}</small></td><td>{{ row.kind || row.itemType || 'Supplier' }}</td><td><span class="rounded bg-slate-700 px-2 py-1">{{ row.signals?.join(', ') || row.status || 'In Stock' }}</span></td><td>{{ row.currentStock !== undefined ? row.currentStock + ' ' + (row.unit || 'units') : row.total !== undefined ? currency(row.total) : row.requestedAmount !== undefined ? currency(row.requestedAmount) : row.lines?.map(l => l.quantity ?? l.accepted).join(', ') || '—' }}</td><td>{{ nextAction(row) }}</td><td><button @click="view(row)">Details</button></td></tr><tr v-if="!pagedRows.length"><td colspan="6" class="text-center text-slate-400">No matching records. Create a request or adjust your filters.</td></tr></tbody></table></div>
          <div class="mt-4 flex items-center justify-between"><span class="text-sm text-slate-400">{{ filteredRows.length }} records · Page {{ currentPage }} / {{ pages }}</span><div class="flex gap-2"><button :disabled="currentPage === 1" @click="currentPage--">Previous</button><button :disabled="currentPage >= pages" @click="currentPage++">Next</button></div></div>
        </template>
      </template>

      <div v-if="selected" class="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-3" @click.self="selected = null"><section class="max-h-[92vh] w-full max-w-5xl overflow-auto rounded-xl border border-slate-600 bg-slate-900 p-6"><header class="flex justify-between"><div><h2 class="text-xl font-semibold">{{ selected.number || selected.name || selected.businessName }}</h2><p class="text-sm text-amber-200">{{ selected.status || selected.signals?.join(', ') }} · {{ nextAction(selected) }}</p></div><button @click="selected = null">Close</button></header>
        <div class="my-4 grid gap-3 rounded-lg border border-slate-700 p-4 sm:grid-cols-4"><div><small class="text-slate-400">Current Status</small><p>{{ selected.status || selected.signals?.join(', ') || 'Active' }}</p></div><div><small class="text-slate-400">Responsible Department</small><p>{{ responsibleDepartment(selected) }}</p></div><div><small class="text-slate-400">Current Owner</small><p>{{ currentOwner(selected) }}</p></div><div><small class="text-slate-400">Next Action</small><p>{{ nextAction(selected) }}</p></div></div>
        <p v-if="error" class="my-3 text-red-300" role="alert">{{ error }}</p><p v-for="issue in selected.matchIssues || []" :key="issue" class="my-2 text-red-300">{{ issue }}</p><div class="my-5 flex flex-wrap gap-2"><button v-for="action in actions(selected)" :key="action.key" @click="runAction(action.key, selected)" :disabled="busy">{{ action.label }}</button></div>
        <dl class="grid gap-3 sm:grid-cols-3"><template v-for="[key, value] in detailFields" :key="key"><div><dt class="text-xs text-slate-400">{{ label(key) }}</dt><dd class="break-words text-sm">{{ formatValue(key, value) }}</dd></div></template></dl>
        <img v-if="selected.imageUrl" :src="selected.imageUrl" alt="Inventory item" class="my-4 max-h-48 rounded" />
        <div v-if="selected.lines?.length" class="my-5 overflow-auto"><table class="w-full text-sm"><thead><tr><th>Item</th><th>Quantity</th><th>Unit price</th><th>Delivered / Accepted / Rejected</th><th>Condition / Notes</th></tr></thead><tbody><tr v-for="line in selected.lines" :key="line.itemId"><td>{{ line.name || itemName(line.itemId) }}</td><td>{{ line.quantity ?? line.ordered }} {{ line.unit }}</td><td>{{ line.unitPrice !== undefined ? currency(line.unitPrice) : '—' }}</td><td>{{ line.delivered ?? '—' }} / {{ line.accepted ?? '—' }} / {{ line.rejected ?? '—' }}</td><td>{{ line.condition }} {{ line.reason }} {{ line.expiryDate }}</td></tr></tbody></table></div>
        <section v-if="selected.kind === 'rfq' && !supplierView" class="my-5"><h3 class="font-semibold">Quotation comparison</h3><div class="overflow-auto"><table class="w-full text-sm"><thead><tr><th>Supplier</th><th>Total</th><th>Lead days</th><th>Payment terms</th><th>Warranty</th><th>Valid until</th></tr></thead><tbody><tr v-for="q in data.records.filter(r => r.kind === 'quotation' && r.rfqId === selected.id)" :key="q.id"><td><button @click="view(q)">{{ supplierName(q.supplierId) }}</button></td><td>{{ currency(q.total) }}</td><td>{{ q.leadDays }}</td><td>{{ q.paymentTerms }}</td><td>{{ q.warranty }}</td><td>{{ q.validUntil }}</td></tr></tbody></table></div><p class="text-xs text-slate-400">Selection requires your evaluation and justification; price alone does not select a supplier.</p></section>
        <section v-if="!selected.kind && selected.currentStock === undefined" class="my-5"><h3 class="font-semibold">Supplier product catalog</h3><p v-for="(product, index) in supplierProducts(selected)" :key="index" class="mt-2 text-sm">{{ product.name || product.itemName || product.productName }} · {{ product.unit || 'units' }} · PHP {{ product.price || product.unitPrice || 'Not quoted' }}</p><p v-if="!supplierProducts(selected).length" class="text-sm text-slate-400">No catalog items recorded. Use Suppliers to manage this business.</p></section>
        <section class="my-5"><h3 class="font-semibold">Related records</h3><div class="mt-2 flex flex-wrap gap-2"><button v-for="r in relatedRecords" :key="r.id" @click="view(r)">{{ r.number || r.name || r.id }} · {{ r.status }}</button></div></section>
        <section v-if="data.records.some(r => r.id === selected.id)"><h3 class="font-semibold">Documents</h3><div class="my-2 flex flex-wrap gap-2"><button v-for="d in history.documents" :key="d.id" @click="download(d)">{{ d.name }} · {{ d.visibility }}</button></div><label class="text-sm">Upload PDF or image (up to 5 MB)<input type="file" accept="application/pdf,image/png,image/jpeg" @change="upload" :disabled="busy" /></label><label v-if="!supplierView" class="my-2 block text-sm"><input type="checkbox" v-model="shareDocument" /> Share with the supplier(s) on this record</label></section>
        <section v-if="history.messages?.length" class="mt-5"><h3 class="font-semibold">Supplier communication</h3><p v-for="m in history.messages" :key="m.id" class="my-3 border-l-2 pl-3">{{ formatDate(m.createdAt) }} · {{ m.from }} · {{ m.channel }}<br />{{ m.message }}</p></section><section v-if="history.history.length" class="mt-5"><h3 class="font-semibold">Activity timeline</h3><p v-for="event in history.history" :key="event.id" class="mt-2 border-l-2 border-amber-500 pl-3 text-sm">{{ formatDate(event.createdAt) }} · {{ event.actorName || event.actorId }} · {{ event.action }} · {{ event.previousStatus }} → {{ event.newStatus }}</p></section>
      </section></div>

      <div v-if="formKind" class="fixed inset-0 z-[60] flex items-center justify-center bg-black/80 p-3"><form @submit.prevent="saveForm" class="max-h-[92vh] w-full max-w-4xl overflow-auto rounded-xl border border-slate-600 bg-slate-900 p-6"><h2 class="mb-4 text-xl font-semibold">{{ formTitle }}</h2><p v-if="formError" class="mb-3 text-red-300" role="alert">{{ formError }}</p>
        <div class="grid gap-4 sm:grid-cols-2"><label v-for="field in formFields" :key="field.key" class="text-sm text-slate-300">{{ field.label }}<select v-if="field.options" v-model="form[field.key]" :multiple="field.multiple" :required="field.required !== false"><option v-if="!field.multiple" value="">Select…</option><option v-for="option in field.options" :key="option.value ?? option" :value="option.value ?? option">{{ option.label ?? option }}</option></select><textarea v-else-if="field.type === 'textarea'" v-model="form[field.key]" :required="field.required !== false" rows="3"></textarea><input v-else v-model="form[field.key]" :type="field.type || 'text'" :required="field.required !== false" :min="field.type === 'number' ? 0 : undefined" :step="field.type === 'number' ? 'any' : undefined" /></label></div>
              <div v-if="form.lines" class="mt-5 space-y-3"><h3 class="font-semibold">{{ formKind === 'receiving' ? 'Quantity and quality inspection' : 'Line items' }}</h3><div v-for="line in form.lines" :key="line.itemId" class="rounded border border-slate-700 p-3"><p class="mb-2 font-medium">{{ line.name || itemName(line.itemId) }}</p><div class="grid gap-2 sm:grid-cols-3"><template v-if="formKind === 'receiving'"><label>Delivered<input type="number" min="0" step="1" v-model="line.delivered" required /></label><label>Accepted<input type="number" min="0" step="1" v-model="line.accepted" required /></label><label>Rejected<input type="number" min="0" step="1" v-model="line.rejected" required /></label><label>Condition<select v-model="line.condition"><option v-for="c in ['Good','Damaged','Defective','Wrong item','Expired','Missing','Other discrepancy']" :key="c">{{ c }}</option></select></label><label>Reason / discrepancy<input v-model="line.reason" /></label><label>Batch / lot<input v-model="line.lot" /></label><label>Expiry<input type="date" v-model="line.expiryDate" /></label><label>Serial number<input v-model="line.serialNumber" /></label><label>Model<input v-model="line.modelNumber" /></label><label>Warranty<input v-model="line.warranty" /></label><label>Packaging<input v-model="line.packaging" /></label></template><template v-else><label>Quantity<input type="number" min="1" step="1" v-model="line.quantity" required /></label><label>Unit price (PHP)<input type="number" min="0" step="0.01" v-model="line.unitPrice" required /></label><p class="self-end pb-2">PHP {{ (Number(line.quantity || 0) * Number(line.unitPrice || 0)).toFixed(2) }}</p></template></div></div><p v-if="formKind !== 'receiving'" class="text-right font-semibold">Total: PHP {{ formTotal.toFixed(2) }}</p></div>
        <p v-if="formKind === 'pay'" class="mt-4 text-sm text-amber-200">This records a payment already made through your bank or external provider. It does not transfer money.</p>
        <div class="mt-6 flex justify-end gap-3"><button type="button" @click="formKind = ''" :disabled="busy">Cancel</button><button class="bg-amber-800" type="submit" :disabled="busy">{{ busy ? 'Saving…' : 'Save and continue' }}</button></div>
      </form></div>
    </main>
  </div>
</template>

<script setup>
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import { useRoute } from 'vue-router'
import { auth } from '@/config/firebaseConfig'
import { OTP_BACKEND_CANDIDATES } from '@/utils/runtimeConfig'
import OwnerSidebar from '@/components/sidebar/OwnerSidebar.vue'
import SupplierSidebar from '@/components/sidebar/SupplierSidebar.vue'
import Swal from 'sweetalert2'
import { dashboardCharts, reportDefinitions, exportReportCsv } from '@/utils/supplyReporting'

const route = useRoute()
const supplierView = computed(() => route.path.startsWith('/supplier/'))
const department = computed(() => supplierView.value ? 'supplier' : route.meta.supplyDepartment || route.params.department || 'inventory')
const page = computed(() => route.params.page || 'dashboard')
const departmentLabel = computed(() => ({ inventory: 'Inventory Management', procurement: 'Procurement Management', logistics: 'Logistics Management', finance: 'Procurement Finance', management: 'Management Overview', supplier: 'Supplier Portal' })[department.value])
const pageTitle = computed(() => ({ dashboard: 'Dashboard', items: department.value === 'logistics' ? 'Receiving & inspection' : 'Inventory List · DSS', requests: 'Requests', orders: 'Purchase Orders', suppliers: 'Supplier List', reports: 'Reports & Traceability', onboarding: 'Inventory Onboarding', budgets: 'Budget Allocations', invoices: 'Invoices & Payments', rfqs: 'RFQs & Quotations' })[page.value] || 'Supply Management')
const intro = computed(() => ({ inventory: 'Monitor stock, review DSS recommendations, and request replenishment.', procurement: 'Source quotations, record your evaluation, and issue funded purchase orders.', logistics: 'Inspect deliveries and onboard only accepted quantities into inventory.', finance: 'Reserve budgets, match invoices to accepted deliveries, and record supplier payments.', supplier: 'Respond to your RFQs, confirm orders, and track invoice and payment status.' })[department.value])
const tabMap = { management: ['dashboard','reports'], inventory: ['dashboard','items','requests','reports'], procurement: ['dashboard','requests','rfqs','orders','suppliers','reports'], logistics: ['dashboard','items','onboarding','requests','reports'], finance: ['dashboard','budgets','requests','invoices','reports'], supplier: ['dashboard','rfqs','orders','invoices','reports'] }
const clinicSupplyPath = (module, targetPage) => ({ finance: `/finance/procurement/${targetPage}`, management: `/management/supply/${targetPage}` })[module] || `/${module}/${targetPage}`
const tabs = computed(() => (tabMap[department.value] || []).map(key => ({ key, label: ({ items: department.value === 'logistics' ? 'Inspection' : 'Inventory List', rfqs: 'RFQs & Quotes', onboarding: 'Onboarding', invoices: 'Invoices & Payments' })[key] || label(key), to: supplierView.value ? `/supplier/supply/${key}` : clinicSupplyPath(department.value, key) })))
const data = ref({ records: [], items: [], suppliers: [], branches: [], movements: [], permissions: [] }), branchId = ref(''), loading = ref(true), busy = ref(false), error = ref(''), notice = ref('')
const selected = ref(null), history = ref({ history: [], documents: [] }), shareDocument = ref(false)
const search = ref(''), status = ref(''), type = ref(''), departmentFilter = ref(''), supplierFilter = ref(''), categoryFilter = ref(''), fromDate = ref(''), toDate = ref(''), sort = ref('newest'), currentPage = ref(1)
const formKind = ref(''), form = ref({}), formFields = ref([]), formTarget = ref(null), formError = ref('')
const can = permission => data.value.permissions.includes(permission) || data.value.permissions.includes('administrator:full_access')
const api = async (path, body) => {
  await auth.authStateReady?.(); const token = await auth.currentUser?.getIdToken(); if (!token) throw Error('Sign in to continue.')
  let last
  for (const base of OTP_BACKEND_CANDIDATES) {
    let response
    try { response = await fetch(base + '/supply' + path, { method: body === undefined ? 'GET' : 'POST', headers: { Authorization: `Bearer ${token}`, 'content-type': 'application/json' }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }) } catch (e) { last = e; continue }
    const result = await response.json(); if (!response.ok || !result.success) throw Error(result.error || 'Unable to complete action.'); return result.data
  }
  throw last || Error('Backend is unavailable.')
}
const load = async (silent = false) => {
  if (!silent) loading.value = true
  try { const result = await api('/workspace' + (branchId.value ? '?branchId=' + encodeURIComponent(branchId.value) : '')); data.value = result; branchId.value = result.branchId || ''; error.value = ''; if(result.supplier || branchId.value) api('/reminders',{branchId:branchId.value}).catch(() => {}); if (selected.value) selected.value = [...result.records, ...result.items, ...result.suppliers].find(r => r.id === selected.value.id) || null }
  catch (e) { error.value = e.message } finally { loading.value = false }
}
const label = key => String(key).replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase())
const currency = cents => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' }).format(Number(cents || 0) / 100)
const timestamp = v => typeof v === 'object' ? (v?._seconds ?? v?.seconds ?? 0) * 1000 : Date.parse(v || '') || 0
const formatDate = v => timestamp(v) ? new Date(timestamp(v)).toLocaleString() : '—'
const supplierName = id => { const s = data.value.suppliers.find(s => s.id === id); return s ? s.businessName || s.name || s.companyName || id : id || '' }
const itemName = id => data.value.items.find(i => i.id === id)?.name || id
const supplierProducts = s => Array.isArray(s.offeredItems) ? s.offeredItems : Array.isArray(s.items) ? s.items : Array.isArray(s.products) ? s.products : Array.isArray(s.supplies) ? s.supplies : []
const kindSets = { management: ['request','procurement','rfq','quotation','evaluation','budget','budgetRequest','financeApproval','budgetAllocation','po','supplierConfirmation','receiving','inspection','discrepancy','invoice','threeWayMatch','payment'], inventory: ['request','receiving','inspection'], procurement: ['procurement','rfq','quotation','evaluation','budgetRequest','financeApproval','po','supplierConfirmation'], logistics: ['po','supplierConfirmation','receiving','inspection','discrepancy'], finance: ['budget','budgetRequest','financeApproval','budgetAllocation','invoice','threeWayMatch','payment','po'], supplier: ['rfq','quotation','po','invoice','payment'] }
const reportKey = ref('')
const availableReports = computed(() => reportDefinitions[department.value] || [])
watch(department, () => { reportKey.value = ''; search.value = '' })
const rows = computed(() => {
  const d = department.value, p = page.value
  if (p === 'items' && d === 'inventory') return data.value.items
  if (p === 'suppliers') return data.value.suppliers
  if (p === 'reports') return (availableReports.value.find(r => r.key === reportKey.value) || availableReports.value[0])?.select(data.value,today()) || []
  const kinds = p === 'rfqs' ? ['rfq','quotation'] : p === 'orders' ? ['po'] : p === 'budgets' ? ['budget'] : p === 'invoices' ? ['invoice','payment'] : p === 'onboarding' ? ['receiving'] : p === 'items' ? ['po','receiving'] : d === 'inventory' ? ['request'] : d === 'logistics' ? ['discrepancy'] : d === 'finance' ? ['budgetRequest'] : ['procurement','budgetRequest','evaluation']
  return data.value.records.filter(r => kinds.includes(r.kind))
})
const statuses = computed(() => [...new Set(rows.value.flatMap(r => r.signals?.length ? r.signals : [r.status || 'In Stock']))].sort())
const types = computed(() => [...new Set(rows.value.map(r => r.kind || r.itemType || 'Supplier'))])
const searchableRows = computed(() => {
  const term=search.value.trim().toLowerCase();if(!term)return rows.value
  const all=[...data.value.records,...data.value.items,...data.value.suppliers,...data.value.movements],direct=all.filter(r=>JSON.stringify(r).toLowerCase().includes(term)),ids=new Set(direct.flatMap(r=>[r.id,...(r.links||[]),r.poId,r.rfqId,r.procurementId,r.invoiceId,r.receivingId,r.supplierId].filter(Boolean)))
  return all.filter(r=>ids.has(r.id)||r.links?.some(id=>ids.has(id))||['poId','rfqId','procurementId','invoiceId','receivingId','supplierId'].some(key=>ids.has(r[key])))
})
const filteredRows = computed(() => searchableRows.value.filter(r => (!status.value || r.status === status.value || r.signals?.includes(status.value)) && (!type.value || (r.kind || r.itemType || 'Supplier') === type.value) && (!departmentFilter.value || String(r.department || '').toLowerCase().includes(departmentFilter.value.toLowerCase())) && (!supplierFilter.value || r.supplierId === supplierFilter.value) && (!categoryFilter.value || String(r.category || '').toLowerCase().includes(categoryFilter.value.toLowerCase())) && (!fromDate.value || timestamp(r.createdAt) >= Date.parse(fromDate.value)) && (!toDate.value || timestamp(r.createdAt) < Date.parse(toDate.value) + 86400000)).sort((a,b) => sort.value === 'name' ? String(a.name || a.number || '').localeCompare(b.name || b.number || '') : (timestamp(b.createdAt) - timestamp(a.createdAt)) * (sort.value === 'oldest' ? -1 : 1)))
const pages = computed(() => Math.max(1, Math.ceil(filteredRows.value.length / 15)))
const pagedRows = computed(() => filteredRows.value.slice((currentPage.value - 1) * 15, currentPage.value * 15))
watch([search,status,type,departmentFilter,supplierFilter,categoryFilter,fromDate,toDate,sort,page,reportKey], () => { currentPage.value = 1 })
watch(department, () => { status.value = ''; type.value = ''; selected.value = null; formKind.value = '' })
const nextAction = r => ({ Draft: 'Creator: complete and submit', Submitted: 'Reviewer: review record', 'Under Review': 'Inventory: decide request', 'Sent to Procurement': 'Procurement: prepare RFQ', Received: 'Procurement: prepare RFQ', 'RFQ Preparation': 'Procurement: send RFQ', Sent: 'Procurement: open RFQ to invited suppliers', Open: r.kind === 'discrepancy' ? 'Logistics: resolve discrepancy' : 'Supplier: submit quotation', 'Quotation Received': 'Suppliers may quote; Procurement closes at deadline', 'Quotations Received': 'Procurement: close RFQ for evaluation', Closed: 'Procurement: begin evaluation', 'Under Evaluation': 'Procurement: select and justify supplier', Evaluation: 'Procurement: select supplier', Selected: 'Finance: review budget', 'For Finance Approval': 'Finance: review funding', 'Finance Review': 'Finance: approve / return', 'Pending Approval': 'Procurement: approve funded PO', Approved: r.kind === 'payment' ? 'Finance: begin external processing' : 'Procurement: issue PO', 'Sent to Supplier': 'Supplier: confirm order', 'Supplier Confirmed': 'Procurement: start confirmed order', Ongoing: 'Logistics: receive and inspect', 'Partially Received': 'Logistics: receive remaining goods', Inspected: 'Logistics: onboard accepted stock', Delivered: 'Supplier / Finance: submit invoice', Matched: 'Finance: approve invoice', Disputed: 'Finance: restart verification after correction', 'Approved for Payment': paymentForInvoice(r) ? 'Finance: advance the payment record' : 'Finance: prepare payment record', Pending: r.kind === 'payment' ? 'Finance: review payment' : 'Review record', 'Under Verification': r.kind === 'payment' ? 'Finance: approve or reject payment' : 'Finance: complete three-way matching', Processing: 'Finance: complete the external payment and record settlement', Paid: 'Payment recorded', Completed: 'Complete', Returned: 'Requester: revise and resubmit', Rejected: 'Review rejection reason' })[r.status] || (r.signals?.includes('For Restocking') ? 'Inventory: review replenishment recommendation' : 'View details')
const cards = computed(() => {
  const rs = data.value.records, count = (kind, states) => rs.filter(r => r.kind === kind && (!states || states.includes(r.status))).length
  if (department.value === 'inventory') return [{ label:'Total Items',value:data.value.items.length },{label:'Total Quantity',value:data.value.items.reduce((s,i)=>s+Number(i.currentStock||0),0)},...['For Restocking','Overstocked','Expiring Soon','Expired','Needs Attention'].map(flag=>({label:flag==='For Restocking'?'Low Stock':flag==='Needs Attention'?'Equipment Needing Attention':flag,value:data.value.items.filter(i=>i.signals?.includes(flag)).length})),{label:'Pending Inventory Requests',value:count('request',['Submitted','Under Review'])}]
  if (department.value === 'finance') { const budgets=rs.filter(r=>r.kind==='budget'), payments=rs.filter(r=>r.kind==='payment'&&r.status==='Paid'), committed=budgets.reduce((s,b)=>s+b.committed,0), spent=budgets.reduce((s,b)=>s+b.spent,0); return [{label:'Total Budget',value:currency(budgets.reduce((s,b)=>s+b.total,0))},{label:'Allocated Budget',value:currency(committed+spent)},{label:'Available Budget',value:currency(budgets.reduce((s,b)=>s+b.total-b.committed-b.spent,0))},{label:'Committed Budget',value:currency(committed)},{label:'Actual Spending',value:currency(spent)},{label:'Pending Budget Requests',value:count('budgetRequest',['Submitted','Finance Review'])},{label:'Approved Budget Requests',value:count('budgetRequest',['Approved'])},{label:'Rejected Budget Requests',value:count('budgetRequest',['Rejected'])},{label:'Pending Invoices',value:count('invoice',['Submitted','Disputed'])},{label:'Invoices Under Verification',value:count('invoice',['Under Verification'])},{label:'Payments Due',value:count('invoice',['Approved for Payment'])},{label:'Payments Completed',value:payments.length},{label:'Total Procurement Spending',value:currency(payments.reduce((s,p)=>s+p.total,0))}] }
  if (department.value === 'logistics') { const receiving=rs.filter(r=>r.kind==='receiving'), lines=receiving.flatMap(r=>r.lines||[]); return [{label:'Expected Deliveries',value:count('po',['Ongoing','Partially Received'])},{label:"Today's Deliveries",value:receiving.filter(r=>r.deliveryDate===today()).length},{label:'Overdue Deliveries',value:rs.filter(r=>r.kind==='po'&&['Ongoing','Partially Received'].includes(r.status)&&r.deliveryDate<today()).length},{label:'Pending Inspections / Onboarding',value:count('receiving',['Inspected'])},{label:'Accepted Deliveries',value:count('receiving',['Onboarded'])},{label:'Partially Accepted',value:count('po',['Partially Received'])},{label:'Rejected Deliveries',value:lines.filter(l=>Number(l.rejected)>0).length},{label:'Damaged Items',value:lines.filter(l=>['Damaged','Defective'].includes(l.condition)).length},{label:'Quantity Discrepancies',value:count('discrepancy',['Open'])}] }
  if (department.value === 'supplier') return [{label:'Open RFQs',value:count('rfq',['Open','Quotation Received'])},{label:'Quotations Submitted',value:count('quotation')},{label:'Awarded Quotations',value:count('quotation',['Selected'])},{label:'Purchase Orders',value:count('po')},{label:'Orders Awaiting Response',value:count('po',['Sent to Supplier'])},{label:'Expected Deliveries',value:count('po',['Ongoing','Partially Received'])},{label:'Invoices',value:count('invoice')},{label:'Payments Paid',value:count('payment',['Paid'])}]
  if (department.value === 'management') { const budgets=rs.filter(r=>r.kind==='budget'), payments=rs.filter(r=>r.kind==='payment'&&r.status==='Paid'); return [{label:'Inventory Items',value:data.value.items.length},{label:'Open Inventory Needs',value:count('request',['Submitted','Under Review','Sent to Procurement'])},{label:'Open RFQs',value:count('rfq',['Open'])},{label:'Active Orders',value:count('po',['Sent to Supplier','Ongoing','Partially Received','Delivered'])},{label:'Pending Finance Actions',value:count('budgetRequest',['Submitted','Finance Review'])+count('invoice',['Submitted','Under Verification','Matched','Approved for Payment'])},{label:'Committed Budget',value:currency(budgets.reduce((s,b)=>s+b.committed,0))},{label:'Actual Spending',value:currency(payments.reduce((s,p)=>s+p.total,0))},{label:'Completed Transactions',value:count('po',['Completed'])}] }
  return [{label:'New Inventory Requests',value:count('procurement',['Received'])},{label:'Procurement Requests',value:count('procurement')},{label:'Open RFQs',value:count('rfq',['Open','Quotation Received'])},{label:'Quotations Received',value:count('quotation')},{label:'Awaiting Evaluation',value:count('rfq',['Closed'])},{label:'Pending Finance Approval',value:count('budgetRequest',['Submitted','Finance Review'])},{label:'Approved Budgets',value:count('budgetRequest',['Approved'])},{label:'Purchase Orders',value:count('po')},{label:'Ongoing Orders',value:count('po',['Ongoing','Partially Received'])},{label:'Overdue Orders',value:rs.filter(r=>r.kind==='po'&&['Ongoing','Partially Received'].includes(r.status)&&r.deliveryDate<today()).length},{label:'Completed Orders',value:count('po',['Completed'])},{label:'Cancelled Orders',value:count('po',['Cancelled'])}]
})
const today = () => new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const groupChart = (title, source, field) => { const counts={}; source.forEach(r=>{const k=r[field]||'Unspecified';counts[k]=(counts[k]||0)+1});const entries=Object.entries(counts).map(([label,value])=>({label,value}));return {title,entries,max:Math.max(1,...entries.map(e=>e.value))} }
const charts = computed(() => dashboardCharts(data.value,department.value))
const alerts = computed(() => [...(department.value==='inventory'?data.value.items.filter(i=>i.signals?.length).map(i=>`${i.name}: ${i.signals.join(', ')}. Suggested replenishment: ${Math.max(0,Number(i.targetStock||i.maxStock||0)-Number(i.currentStock||0))} ${i.unit||'units'}.`):[]),...data.value.records.filter(r=>kindSets[department.value]?.includes(r.kind)&&((r.kind==='rfq'&&['Sent','Open','Quotation Received'].includes(r.status)&&r.deadline<=today())||(r.kind==='po'&&['Supplier Confirmed','Ongoing','Partially Received'].includes(r.status)&&r.deliveryDate<today())||['Disputed','Returned','Rejected'].includes(r.status))).map(r=>`${r.number}: ${r.status}. ${nextAction(r)}`)])
const view = async row => { selected.value=row; history.value={history:[],documents:[]};shareDocument.value=false;if(row.kind&&data.value.records.some(r=>r.id===row.id))try{history.value=await api(`/records/${row.id}/history`)}catch(e){error.value=e.message} }
const internalDetailKeys = new Set(['id','lines','links','imageUrl','ownerId','supplierUserId','branchId','clinicOwnerId','createdBy','updatedBy','reviewedBy','approvedBy','processedBy','receivedBy','inspectedBy','verifiedBy','allocatedBy','paymentId','invoiceId','poId','rfqId','procurementId','requestId','inventoryItemId','receivingId','inspectionId','evaluationId','budgetRequestId','financeApprovalId','budgetAllocationId','supplierConfirmationId','threeWayMatchId'])
const detailFields = computed(() => Object.entries(selected.value || {}).filter(([key, value]) => !internalDetailKeys.has(key) && !/Ids$/.test(key) && typeof value !== 'object'))
const formatValue = (key,value) => /^(total|subtotal|tax|delivery|otherCharges|discount|amount|requestedAmount|approvedAmount|committed|spent|paidAmount|committedAmount|estimatedCost)$/.test(key) ? currency(value) : value === true ? 'Yes' : value === false ? 'No' : String(value)
const responsibleDepartment = record => ['budget','budgetRequest','financeApproval','budgetAllocation','invoice','threeWayMatch','payment'].includes(record.kind) ? 'Finance' : ['receiving','inspection','discrepancy'].includes(record.kind) || record.kind === 'po' && ['Supplier Confirmed','Ongoing','Partially Received','Delivered'].includes(record.status) ? 'Logistics' : record.kind === 'request' || record.currentStock !== undefined ? 'Inventory' : record.kind ? 'Procurement' : 'Supplier Management'
const currentOwner = record => {
  if (!record.kind && record.currentStock === undefined) return record.contact || record.contactPerson || 'Supplier contact'
  return record.officerName || record.receivedByName || record.inspectedByName || record.approvedByName || record.reviewedByName || record.processedByName || (record.supplierId ? supplierName(record.supplierId) : responsibleDepartment(record))
}
const relatedRecords = computed(() => { const s=selected.value;if(!s)return [];const ids=new Set([s.id,...(s.links||[]),s.inventoryItemId,s.poId,s.receivingId,...(s.receivingIds||[])]);return [...data.value.records,...data.value.items,...data.value.movements].filter(r=>r.id!==s.id&&(ids.has(r.id)||r.links?.includes(s.id)||r.lines?.some(l=>l.itemId===s.id)||r.supplierId===s.id||r.supplierIds?.includes(s.id)||['poId','rfqId','procurementId','invoiceId','receivingId','inspectionId','financeApprovalId','budgetAllocationId','supplierConfirmationId','threeWayMatchId'].some(k=>r[k]===s.id))) })
const paymentForInvoice = invoice => data.value.records.find(record => record.kind === 'payment' && record.invoiceId === invoice.id && record.status !== 'Rejected')
const invoiceForPayment = payment => data.value.records.find(record => record.kind === 'invoice' && record.id === payment.invoiceId)
const actions = r => {
  const list=[], add=(key,text,condition)=>{if(condition)list.push({key,label:text})}, state=(...s)=>s.includes(r.status), staff=!supplierView.value
  add('editItem','Edit item / stock adjustment',r.currentStock!==undefined&&can('inventory:create'));add('requestItem','Request replenishment',r.currentStock!==undefined&&can('inventory:create'))
  if(r.kind==='request'){add('editRequest','Edit request',can('inventory:create')&&state('Draft','Returned'));add('submit','Submit request',can('inventory:create')&&state('Draft','Returned'));add('review','Start review',can('inventory:review')&&state('Submitted'));for(const k of ['approve','return','reject'])add(k,label(k),can('inventory:review')&&r.createdBy!==data.value.uid&&state('Submitted','Under Review'))}
  if(r.kind==='procurement'){add('review','Start procurement review',can('procurement:review')&&state('Received'));add('resource','Restart sourcing',can('procurement:review')&&!state('Completed'));add('rfq','Prepare RFQ',can('procurement:create')&&state('Received','Under Review'))}
  if(r.kind==='rfq'){add('editRfq','Edit draft RFQ',can('procurement:review')&&state('Draft'));add('cancel','Cancel RFQ',can('procurement:review')&&state('Draft','Sent','Open','Quotation Received','Closed','Under Evaluation'));add('send','Send / record RFQ',can('procurement:review')&&state('Draft'));add('open','Open RFQ',can('procurement:review')&&state('Sent'));add('close','Close for evaluation',can('procurement:review')&&state('Open','Quotation Received'));add('evaluate','Start evaluation',can('procurement:review')&&state('Closed'));add('quotation','Submit quotation',state('Open','Quotation Received')&&(supplierView.value||r.mode==='Manual'&&can('procurement:create')))}
  if(r.kind==='quotation'){add('revise','Revise quotation',state('Submitted')&&(supplierView.value||r.mode==='Manual'&&can('procurement:create')));add('select','Select supplier & request budget',state('Submitted')&&can('procurement:review'))}
  if(r.kind==='budgetRequest'){for(const k of ['review','approve','return','reject'])add(k,label(k),can('finance:payables:approve')&&r.createdBy!==data.value.uid&&state('Submitted','Finance Review'));add('resubmit','Revise & resubmit',can('procurement:review')&&state('Returned','Rejected'))}
  if(r.kind==='po'){add('submitPo','Submit PO for approval',can('procurement:review')&&state('Draft'));add('approvePo','Approve funded PO',can('procurement:review')&&state('Pending Approval'));add('issue','Issue purchase order',can('procurement:review')&&state('Approved'));for(const k of ['confirm','decline','clarify'])add(k,label(k)+' order',state('Sent to Supplier')&&(supplierView.value||r.mode==='Manual'&&can('procurement:review')));add('startOrder','Start confirmed order',can('procurement:review')&&state('Supplier Confirmed'));add('resend','Respond & resend',can('procurement:review')&&state('Rejected','Clarification Requested'));add('cancel','Cancel order',can('procurement:review')&&state('Draft','Pending Approval','Approved','Sent to Supplier','Supplier Confirmed','Ongoing','Rejected','Clarification Requested'));add('receiving','Record delivery inspection',can('orders:update')&&state('Ongoing','Partially Received'));add('invoice','Submit invoice',state('Delivered','Partially Received')&&(supplierView.value||r.mode==='Manual'&&can('finance:payables:approve')))}
  if(r.kind==='receiving')add('onboard','Onboard accepted inventory',can('orders:update')&&state('Inspected'))
  if(r.kind==='discrepancy')add('resolve','Resolve discrepancy',can('orders:update')&&state('Open'))
  if(r.kind==='invoice'){const payment=paymentForInvoice(r);add('reviseInvoice','Correct invoice',state('Submitted','Disputed')&&(supplierView.value||r.mode==='Manual'&&can('finance:payables:approve')));add('startVerification','Start invoice verification',can('finance:payables:approve')&&state('Submitted','Disputed'));add('verify','Run three-way match',can('finance:payables:approve')&&state('Under Verification'));add('approve','Approve for payment',can('finance:payables:approve')&&r.createdBy!==data.value.uid&&r.verifiedBy!==data.value.uid&&state('Matched'));add('preparePayment','Prepare payment record',can('finance:payables:approve')&&state('Approved for Payment')&&!payment)}
  if(r.kind==='payment'){add('reviewPayment','Start payment verification',can('finance:payables:approve')&&state('Pending'));add('approvePayment','Approve payment',can('finance:payables:approve')&&r.createdBy!==data.value.uid&&state('Under Verification'));add('rejectPayment','Reject payment',can('finance:payables:approve')&&state('Pending','Under Verification'));add('resubmitPayment','Revise and resubmit payment',can('finance:payables:approve')&&state('Rejected'));add('startPayment','Start external processing',can('finance:payables:settle')&&state('Approved'));add('settlePayment','Record completed external payment',can('finance:payables:settle')&&state('Processing')&&invoiceForPayment(r)?.status==='Approved for Payment')}
  if(['rfq','po'].includes(r.kind)&&!state('Draft')&&(supplierView.value||can('procurement:create')))add('message','Supplier communication',true);
  return list
}
const field=(key,text,type='text',required=true)=>({key,label:text,type,required})
const selectField=(key,text,options,multiple=false,required=true)=>({key,label:text,options,multiple,required})
const itemOptions=()=>data.value.items.map(i=>({value:i.id,label:i.name}))
const supplierOptions=()=>data.value.suppliers.filter(s=>s.status==='Active').map(s=>({value:s.id,label:supplierName(s.id)}))
const normalizedCatalogValue=value=>String(value||'').trim().toLowerCase()
const supplierCanProvideLine=(supplier,line)=>supplierProducts(supplier).some(product=>{
  const sameCatalogItem=supplier.id===line.supplierId&&String(product.id||'')===String(line.supplierCatalogItemId||'')
  const sameSupply=normalizedCatalogValue(product.name||product.itemName||product.productName)===normalizedCatalogValue(line.name)
  const sameCategory=!line.category||normalizedCatalogValue(catalogCategory(product))===normalizedCatalogValue(line.category)
  return sameCatalogItem||(sameSupply&&sameCategory)
})
const procurementSupplierOptions=procurement=>data.value.suppliers.filter(s=>s.status==='Active'&&(procurement?.lines||[]).every(line=>supplierCanProvideLine(s,line))).map(s=>({value:s.id,label:supplierName(s.id)}))
const moneyFields=()=>['tax','delivery','otherCharges','discount'].map(k=>field(k,label(k)+' (PHP)','number',false))
const catalogSuppliers=()=>data.value.suppliers.filter(s=>s.status==='Active'&&supplierProducts(s).length).map(s=>({value:s.id,label:supplierName(s.id)}))
const selectedCatalogSupplier=()=>data.value.suppliers.find(s=>s.id===form.value.catalogSupplierId)
const catalogCategory=product=>String(product.category||product.categoryGroup||product.customCategory||'Uncategorized')
const catalogCategories=()=>[...new Set(supplierProducts(selectedCatalogSupplier()||{}).map(catalogCategory))].sort().map(value=>({value,label:value}))
const catalogItems=()=>supplierProducts(selectedCatalogSupplier()||{}).filter(product=>!form.value.catalogCategory||catalogCategory(product)===form.value.catalogCategory).map(product=>({value:product.id,label:`${product.name||product.itemName||product.productName||'Unnamed supply'}${product.measurementUnit||product.unit?` · ${product.measurementUnit||product.unit}`:''}`}))
const selectedCatalogItem=()=>supplierProducts(selectedCatalogSupplier()||{}).find(product=>product.id===form.value.catalogItemId)
const selectedRequestSupplier=()=>data.value.suppliers.find(s=>s.id===form.value.supplierId)
const requestCategories=()=>[...new Set(supplierProducts(selectedRequestSupplier()||{}).map(catalogCategory))].sort().map(value=>({value,label:value}))
const requestCatalogItems=()=>supplierProducts(selectedRequestSupplier()||{}).filter(product=>!form.value.catalogCategory||catalogCategory(product)===form.value.catalogCategory).map(product=>({value:product.id,label:product.name||product.itemName||product.productName||'Unnamed supply'}))
const selectedRequestCatalogItem=()=>supplierProducts(selectedRequestSupplier()||{}).find(product=>product.id===form.value.supplierCatalogItemId)
const requestFormFields=()=>[selectField('supplierId','Supplier',catalogSuppliers()),selectField('catalogCategory','Supply category',requestCategories()),selectField('supplierCatalogItemId','Supply',requestCatalogItems()),field('quantity','Requested quantity','number'),field('minStock','Restocking threshold','number'),field('targetStock','Target stock','number'),field('maxStock','Maximum stock','number'),field('location','Storage location'),field('department','Department'),field('reason','Reason / specifications','textarea'),selectField('priority','Priority',['Low','Normal','High','Urgent']),field('requiredDate','Required date','date'),field('estimatedCost','Estimated cost (PHP)','number')]
const catalogRequired=()=>!formTarget.value||Boolean(formTarget.value.supplierCatalogItemId)
const inventoryFormFields=()=>[
  selectField('catalogSupplierId','Supplier',catalogSuppliers(),false,catalogRequired()),
  selectField('catalogCategory','Supply category',catalogCategories(),false,catalogRequired()),
  selectField('catalogItemId','Supply',catalogItems(),false,catalogRequired()),
  ...['currentStock','minStock','targetStock','maxStock'].map(k=>field(k,k==='currentStock'?'Opening quantity':label(k),'number')),
  field('location','Storage location'),selectField('itemType','Item type',['Material','Equipment']),selectField('consumability','Material classification',['Consumable','Non-consumable']),
  field('expiryDate','Expiration date','date',false),selectField('condition','Condition',['Good','Damaged','Defective','Under repair']),field('serialNumber','Serial number','text',false),field('modelNumber','Model number','text',false),field('warranty','Warranty','text',false),field('adjustmentReason','Reason for opening stock / change','textarea')
]
const refreshInventoryFields=()=>{ if(formKind.value==='item') formFields.value=inventoryFormFields() }
const openItem = item => { const supplierId=item?.supplierId||''; const source=data.value.suppliers.find(s=>s.id===supplierId); const product=supplierProducts(source||{}).find(p=>p.id===item?.supplierCatalogItemId); formTarget.value=item||null;formKind.value='item';formError.value='';form.value={name:'',currentStock:0,minStock:1,targetStock:10,maxStock:20,itemType:'Material',consumability:'Consumable',unit:'pieces',costPrice:0,...item,catalogSupplierId:supplierId,catalogCategory:product?catalogCategory(product):'',catalogItemId:item?.supplierCatalogItemId||'',adjustmentReason:''};refreshInventoryFields() }
watch(()=>form.value.catalogSupplierId,(supplierId,previous)=>{ if(formKind.value!=='item'||supplierId===previous)return; form.value.catalogCategory='';form.value.catalogItemId='';form.value.supplierId=supplierId||'';refreshInventoryFields() })
watch(()=>form.value.catalogCategory,(category,previous)=>{ if(formKind.value!=='item'||category===previous)return; form.value.catalogItemId='';refreshInventoryFields() })
watch(()=>form.value.catalogItemId,(itemId,previous)=>{ if(formKind.value!=='item'||itemId===previous)return; const product=selectedCatalogItem(); const supplier=selectedCatalogSupplier(); if(!product||!supplier)return; Object.assign(form.value,{supplierId:supplier.id,supplierCatalogItemId:product.id,name:product.name||product.itemName||product.productName||'',category:catalogCategory(product),description:product.description||product.specifications||'',unit:product.measurementUnit||product.unit||'units',costPrice:Number(product.price||product.unitCost||0),imageUrl:product.imageUrl||'',supplierCatalogItemId:product.id});refreshInventoryFields() })
watch(()=>form.value.supplierId,(supplierId,previous)=>{if(formKind.value!=='request'||supplierId===previous)return;form.value.catalogCategory='';form.value.supplierCatalogItemId='';formFields.value=requestFormFields()})
watch(()=>form.value.catalogCategory,(category,previous)=>{if(formKind.value!=='request'||category===previous)return;form.value.supplierCatalogItemId='';formFields.value=requestFormFields()})
watch(()=>form.value.supplierCatalogItemId,(itemId,previous)=>{if(formKind.value!=='request'||itemId===previous)return;const product=selectedRequestCatalogItem();if(!product)return;form.value.estimatedCost=Number(product.price||product.unitCost||0)*Number(form.value.quantity||1);formFields.value=requestFormFields()})
const openForm = (kind, target=null) => {
  formKind.value=kind;formTarget.value=target;formError.value='';form.value={};const f=[]
  if(kind==='message'){form.value={supplierId:supplierView.value?data.value.supplierIds[0]:target.supplierId||'',channel:'Email'};if(!supplierView.value)f.push(selectField('supplierId','Supplier',supplierOptions().filter(s=>target.supplierId===s.value||target.supplierIds?.includes(s.value))));if(target.mode==='Manual')f.push(selectField('channel','Communication channel',['Email','Phone','Physical document','External platform']));f.push(field('message','Message / communication record','textarea'))}
  if(kind==='editRequest'){form.value={...target,quantity:target.lines[0].quantity,estimatedCost:Number(target.estimatedCost||0)/100};delete form.value.lines;f.push(field('quantity','Requested quantity','number'),field('department','Department'),field('reason','Reason','textarea'),field('requiredDate','Required date','date'),selectField('priority','Priority',['Low','Normal','High','Urgent']),field('estimatedCost','Estimated cost (PHP)','number'))}
  if(kind==='editRfq'){form.value={...target};delete form.value.lines;f.push(field('deadline','Quotation deadline','date'),field('deliveryDate','Required delivery date','date'),field('deliveryLocation','Delivery location'),field('terms','Terms','textarea'),field('conditions','Conditions','textarea',false),field('contact','Contact'))}
  if(kind==='request'){form.value={supplierId:route.query.supplierId||'',catalogCategory:'',supplierCatalogItemId:'',quantity:1,minStock:1,targetStock:10,maxStock:20,location:'',department:'Inventory',priority:'Normal',requiredDate:today(),estimatedCost:0,reason:''};f.push(...requestFormFields())}
  if(kind==='supplier')f.push(field('name','Company name'),field('contactPerson','Contact person'),field('email','Email','email',false),field('phone','Phone','text',false),field('address','Address','textarea',false),field('category','Category','text',false),field('registrationNumber','Business registration','text',false));
  if(kind==='budget')f.push(field('department','Department'),field('category','Budget category'),field('total','Total budget (PHP)','number'))
  if(kind==='rfq'){const eligibleSuppliers=procurementSupplierOptions(target);form.value={mode:'Online',supplierIds:eligibleSuppliers.filter(s=>target.lines?.some(line=>(line.preferredSupplierId||line.supplierId)===s.value)).map(s=>s.value),deliveryDate:target.requiredDate,deadline:today()};f.push(selectField('mode','Procurement mode',['Manual','Online']),selectField('supplierIds','Invited suppliers',eligibleSuppliers,true),field('deadline','Quotation deadline','date'),field('deliveryDate','Required delivery date','date'),field('deliveryLocation','Delivery location'),field('terms','Terms and specifications','textarea'),field('conditions','Conditions','textarea',false),field('contact','Procurement contact'),field('method','Procurement method'),field('strategy','Supplier strategy','textarea'))}
  if(['quotation','revise','invoice','reviseInvoice'].includes(kind)){
    form.value={lines:target.lines.map(l=>({...l,unitPrice:kind==='quotation'?0:Number(l.unitPrice||0)/100})),tax:Number(target.tax||0)/100,delivery:Number(target.delivery||0)/100,otherCharges:Number(target.otherCharges||0)/100,discount:Number(target.discount||0)/100,validUntil:target.validUntil||today(),leadDays:target.leadDays||0,paymentTerms:target.paymentTerms||'',warranty:target.warranty||'',invoiceNumber:target.invoiceNumber||'',invoiceDate:today(),dueDate:today(),supplierId:data.value.supplierIds?.[0]||''}
    if(kind==='quotation'&&!supplierView.value)f.push(selectField('supplierId','Supplier',supplierOptions().filter(s=>target.supplierIds.includes(s.value))))
    if(kind==='invoice'||kind==='reviseInvoice')f.push(field('invoiceNumber','Supplier invoice number'),field('invoiceDate','Invoice date','date'),field('dueDate','Due date','date'))
    else f.push(field('validUntil','Quotation valid until','date'),field('leadDays','Delivery lead time (days)','number'),field('paymentTerms','Payment terms'),field('warranty','Warranty','text',false),field('notes','Notes / availability','textarea',false))
    f.push(...moneyFields())
  }
  if(kind==='reviseInvoice')f.push(field('remarks','Reason for invoice revision','textarea'));
  if(kind==='select')f.push(field('recommendation','Evaluation recommendation','textarea'),field('justification','Supplier selection justification','textarea'),field('category','Budget category'))
  if(kind==='approve'&&target.kind==='budgetRequest'){form.value.approvedAmount=target.requestedAmount/100;f.push(selectField('budgetId','Department budget',data.value.records.filter(r=>r.kind==='budget').map(b=>({value:b.id,label:`${b.department} · ${b.category} · available ${currency(b.total-b.committed-b.spent)}`}))),field('approvedAmount','Approved amount (PHP)','number'),field('remarks','Finance decision remarks','textarea'))}
  if(['return','reject','resubmit','decline','clarify','resend','cancel','resolve','resource','approvePayment','rejectPayment','resubmitPayment'].includes(kind))f.push(field('remarks','Reason / resolution details','textarea'))
  if(kind==='resolve')f.unshift(selectField('resolutionType','Resolution type',['Return to supplier','Replacement','Credit','Refund','Other resolution']))
  if(kind==='submit'&&target.status==='Returned'){form.value={reason:target.reason,quantity:target.lines[0].quantity};f.push(field('reason','Revised reason','textarea'),field('quantity','Revised quantity','number'))}
  if(kind==='confirm'){form.value.deliveryDate=target.deliveryDate;f.push(field('deliveryDate','Confirmed delivery date','date'),field('remarks','Supplier confirmation details','textarea'))}
  if(kind==='receiving'){form.value={deliveryDate:today(),lines:target.lines.map(l=>({...l,delivered:Math.max(0,l.quantity-Number(target.accepted?.[l.itemId]||0)),accepted:Math.max(0,l.quantity-Number(target.accepted?.[l.itemId]||0)),rejected:0,condition:'Good',reason:'',expiryDate:''}))};f.push(field('reference','Delivery reference'),field('deliveryDate','Delivery date','date'),field('notes','Inspection notes','textarea',false))}
  if(kind==='pay'){form.value={method:'Manual/External',paymentDate:today()};f.push(selectField('method','Payment method',['Manual/External','Electronic']),field('reference','Bank / external payment reference'),field('paymentDate','Payment date','date'),selectField('proofId','Uploaded payment evidence',history.value.documents.map(d=>({value:d.id,label:d.name}))))}
  formFields.value=f
}
const formTitle=computed(()=>formKind.value==='item'?'Inventory item':label(formKind.value)+' '+(formTarget.value?.number||''))
const formTotal=computed(()=>Math.max(0,(form.value.lines||[]).reduce((sum,l)=>sum+Number(l.quantity||0)*Number(l.unitPrice||0),0)+Number(form.value.tax||0)+Number(form.value.delivery||0)+Number(form.value.otherCharges||0)-Number(form.value.discount||0)))
const runAction=async(action,target)=>{
  if(action==='editItem')return openItem(target)
  if(action==='requestItem')return openForm('request',target)
  if(action==='settlePayment'){const invoice=invoiceForPayment(target);if(!invoice){error.value='The linked invoice is unavailable.';return}try{history.value=await api(`/records/${target.id}/history`)}catch(e){error.value=e.message;return}return openForm('pay',invoice)}
  if(['editRequest','editRfq','resource','message','rfq','quotation','revise','reviseInvoice','select','receiving','invoice','pay','return','reject','resubmit','confirm','decline','clarify','resend','cancel','resolve','approvePayment','rejectPayment','resubmitPayment'].includes(action)||(action==='approve'&&target.kind==='budgetRequest')||(action==='submit'&&target.status==='Returned'))return openForm(action,target)
  const answer=await Swal.fire({title:label(action)+' '+target.number+'?',text:'This action updates the linked workflow records.',icon:'question',showCancelButton:true,confirmButtonText:'Confirm'})
  if(!answer.isConfirmed)return
  busy.value=true;try{await api(`/records/${target.id}/actions`,{action});notice.value='Record updated.';await load(true);if(selected.value)await view(selected.value)}catch(e){error.value=e.message}finally{busy.value=false}
}
const saveForm=async()=>{busy.value=true;formError.value='';try{const kind=formKind.value,target=formTarget.value;let path='/records',body={...form.value,kind,branchId:target?.branchId||branchId.value};if(kind==='message'){path='/records/'+target.id+'/messages';body={...form.value}}else if(kind==='supplier'){path='/suppliers'}else if(kind==='item'){path='/items';body={...form.value,branchId:branchId.value,...(target?{id:target.id}:{})}}else if(['rfq','quotation','receiving','invoice'].includes(kind)){body[kind==='rfq'?'procurementId':kind==='quotation'?'rfqId':'poId']=target.id}else if(!['request','budget'].includes(kind)){path=`/records/${target.id}/actions`;body={...form.value,action:kind}}await api(path,body);formKind.value='';notice.value='Saved. Open Details to view related records and the next action.';await load(true);if(selected.value)await view(selected.value)}catch(e){formError.value=e.message}finally{busy.value=false}}
const upload=async event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){error.value='File must be 5 MB or smaller.';return}busy.value=true;try{const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});await api(`/records/${selected.value.id}/documents`,{name:file.name,contentType:file.type,data:base64,visibility:shareDocument.value?'supplier':'internal'});await view(selected.value)}catch(e){error.value=e.message}finally{busy.value=false;event.target.value=''}}
const download=async document=>{try{const result=await api('/documents/'+document.id);window.open(result.url,'_blank','noopener,noreferrer')}catch(e){error.value=e.message}}
const exportCsv=()=>{const url=URL.createObjectURL(new Blob([exportReportCsv(filteredRows.value)],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=department.value+"-"+page.value+"-"+today()+".csv";a.click();URL.revokeObjectURL(url)}
let timer
onMounted(async()=>{await load();if(department.value==='inventory'&&page.value==='requests'&&route.query.supplierId&&can('inventory:create'))openForm('request');timer=setInterval(()=>{if(!busy.value&&!formKind.value)load(true)},60000)})
onUnmounted(()=>clearInterval(timer))
</script>

<style scoped>
input:not([type=checkbox]),select,textarea{display:block;width:100%;margin-top:.3rem;border:1px solid #475569;border-radius:.5rem;background:#1e293b;color:#f1f5f9;padding:.55rem .7rem}button{border:1px solid #64748b;border-radius:.5rem;padding:.5rem .8rem;font-size:.85rem}button:hover:not(:disabled){background:#334155}button:disabled{opacity:.45;cursor:not-allowed}th,td{padding:.8rem;vertical-align:top}th{font-size:.75rem;color:#cbd5e1}select[multiple]{min-height:7rem}input[type=checkbox]{width:auto}
.module-tabs{display:flex;flex-wrap:wrap;gap:.15rem;border-bottom:1px solid #475569}.module-tab{position:relative;display:inline-flex;align-items:center;padding:.65rem .95rem;color:#94a3b8;font-size:.875rem;font-weight:600;transition:color .15s ease}.module-tab:hover{color:#f8fafc}.module-tab-active{color:#fbbf24}.module-tab-active::after{position:absolute;right:.8rem;bottom:-1px;left:.8rem;height:2px;background:#fbbf24;content:''}.module-actions{display:flex;flex-wrap:wrap;gap:.5rem;align-items:center}.module-action{display:inline-flex;align-items:center;gap:.45rem;border:1px solid #64748b;border-radius:.5rem;padding:.5rem .8rem;color:#e2e8f0;font-size:.85rem;line-height:1.25;transition:background .15s ease,border-color .15s ease}.module-action:hover{border-color:#f59e0b;background:#334155}.module-action span{display:inline-grid;height:1.15rem;width:1.15rem;place-items:center;border-radius:.25rem;background:#334155;color:#fbbf24;font-size:1rem;font-weight:700;line-height:1}
</style>
