<template>
  <div class="module-theme flex min-h-screen bg-slate-900 text-slate-100"><SupplierSidebar />
    <main class="min-w-0 flex-1 p-4 md:p-8"><div class="mx-auto max-w-3xl"><header class="mb-6"><p class="text-xs font-semibold uppercase tracking-[.2em] text-amber-300">Supplier Portal</p><h1 class="mt-2 text-3xl font-bold">Clinic Messages</h1><p class="mt-2 text-sm text-slate-400">Chat with the clinic linked to your supplier account. Use an RFQ or Purchase Order message for transaction-specific questions.</p></header>
      <p v-if="error" class="mb-4 rounded border border-red-600 bg-red-950/30 p-3 text-sm text-red-200">{{ error }}</p><div v-if="loading" class="text-slate-400">Loading messages…</div><template v-else><label v-if="suppliers.length > 1" class="mb-4 block text-sm">Supplier account<select v-model="supplierId"><option v-for="supplier in suppliers" :key="supplier.id" :value="supplier.id">{{ supplier.businessName || supplier.name }}</option></select></label><section class="chat-shell"><div class="chat-heading"><strong>{{ currentSupplier?.businessName || currentSupplier?.name || 'Clinic chat' }}</strong><span>General clinic communication</span></div><div ref="thread" class="chat-thread"><p v-if="!messages.length" class="chat-empty">No messages yet. Start the conversation with the clinic.</p><article v-for="message in messages" :key="message.id" class="bubble" :class="message.from === 'Supplier' ? 'mine' : 'theirs'"><p>{{ message.message }}</p><small>{{ message.from }} · {{ date(message.createdAt) }}</small></article></div><form class="chat-compose" @submit.prevent="send"><textarea v-model.trim="draft" rows="3" maxlength="4000" placeholder="Write a message…" required></textarea><button :disabled="sending || !draft">{{ sending ? 'Sending…' : 'Send message' }}</button></form></section></template>
    </div></main>
  </div>
</template>
<script setup>
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import SupplierSidebar from '@/components/sidebar/SupplierSidebar.vue'
import { auth } from '@/config/firebaseConfig'
import { OTP_BACKEND_CANDIDATES } from '@/utils/runtimeConfig'
const loading=ref(true),sending=ref(false),error=ref(''),suppliers=ref([]),supplierId=ref(''),messages=ref([]),draft=ref(''),thread=ref(null)
const currentSupplier=computed(()=>suppliers.value.find(s=>s.id===supplierId.value))
const date=value=>value?new Date((value._seconds||value.seconds||0)*1000).toLocaleString():'Just now'
const api=async(path,body)=>{await auth.authStateReady?.();const token=await auth.currentUser?.getIdToken();if(!token)throw Error('Sign in to continue.');let last;for(const base of OTP_BACKEND_CANDIDATES){try{const response=await fetch(base+'/supply'+path,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok||!result.success)throw Error(result.error);return result.data}catch(e){last=e}}throw last||Error('Chat service is unavailable.')}
const scroll=async()=>{await nextTick();thread.value?.scrollTo({top:thread.value.scrollHeight,behavior:'smooth'})}
const load=async()=>{if(!supplierId.value)return;try{messages.value=(await api('/chat?supplierId='+encodeURIComponent(supplierId.value))).messages||[];await scroll()}catch(e){error.value=e.message}}
const send=async()=>{sending.value=true;try{await api(`/chat/${supplierId.value}/messages`,{message:draft.value});draft.value='';await load()}catch(e){error.value=e.message}finally{sending.value=false}}
onMounted(async()=>{try{const workspace=await api('/workspace');suppliers.value=(workspace.supplierIds||[]).map(id=>({id,name:id}));supplierId.value=suppliers.value[0]?.id||'';await load()}catch(e){error.value=e.message}finally{loading.value=false}});watch(supplierId,load)
</script>
<style scoped>select,textarea{display:block;width:100%;margin-top:.35rem;border:1px solid #475569;border-radius:.5rem;background:#1e293b;padding:.65rem;color:#f8fafc}.chat-shell{overflow:hidden;border:1px solid #334155;border-radius:.8rem;background:#020617}.chat-heading{display:flex;justify-content:space-between;padding:1rem;border-bottom:1px solid #334155}.chat-heading span{font-size:.75rem;color:#94a3b8}.chat-thread{min-height:340px;max-height:55vh;overflow:auto;padding:1rem}.bubble{max-width:80%;margin:.55rem 0;border-radius:.75rem;padding:.65rem .8rem}.mine{margin-left:auto;background:#166534}.theirs{background:#1e293b}.bubble small{display:block;margin-top:.35rem;color:#cbd5e1;font-size:.65rem}.chat-empty{padding:4rem 1rem;text-align:center;color:#94a3b8}.chat-compose{border-top:1px solid #334155;padding:1rem}.chat-compose button{margin-top:.6rem;border:0;border-radius:.5rem;background:#d97706;padding:.55rem .9rem;color:#fff}.chat-compose button:disabled{opacity:.45}</style>
