<template>
  <div class="flex min-h-screen bg-slate-900 text-white"><OwnerSidebar />
    <main class="flex-1 p-4 md:p-8"><div class="mx-auto max-w-5xl space-y-6">
      <header><h1 class="text-3xl font-bold">Walk-In Desk</h1><p class="mt-1 text-slate-400">Register a client, create an approved walk-in appointment, then collect payment.</p></header>
      <p v-if="error" class="rounded-lg border border-rose-500/50 bg-rose-950/30 p-3 text-rose-200">{{ error }}</p>
      <section class="rounded-xl border border-slate-700 bg-slate-800 p-5"><h2 class="text-lg font-semibold">1. Client</h2>
        <div class="mt-4 grid gap-3 md:grid-cols-2"><select v-model="form.clientId" class="input"><option value="">Select an existing client</option><option v-for="client in clients" :key="client.id" :value="client.id">{{ client.fullName }} · {{ client.phone || 'No phone' }}</option></select><button class="btn secondary" @click="showNewClient = !showNewClient">{{ showNewClient ? 'Use existing client' : 'Register new client' }}</button></div>
        <div v-if="showNewClient" class="mt-4 grid gap-3 md:grid-cols-2"><input v-model.trim="newClient.firstName" class="input" placeholder="First name" /><input v-model.trim="newClient.lastName" class="input" placeholder="Last name" /><input v-model.trim="newClient.phone" class="input" placeholder="Phone number" /><input v-model.trim="newClient.email" class="input" placeholder="Email (optional)" /><button class="btn md:col-span-2" :disabled="busy" @click="createClient">Save walk-in client</button></div>
      </section>
      <section class="rounded-xl border border-slate-700 bg-slate-800 p-5"><h2 class="text-lg font-semibold">2. Appointment</h2>
        <div class="mt-4 grid gap-3 md:grid-cols-2"><select v-model="form.serviceId" class="input"><option value="">Select service</option><option v-for="service in services" :key="service.id" :value="service.id">{{ service.name }} · ₱{{ money(service.price) }}</option></select><select v-model="form.practitionerId" class="input"><option value="">Select practitioner</option><option v-for="person in practitioners" :key="person.id" :value="person.id">{{ person.fullName }}</option></select><input v-model="form.date" type="date" class="input" :min="today" /><input v-model="form.time" type="time" class="input" /><textarea v-model.trim="form.notes" class="input md:col-span-2" rows="2" placeholder="Notes (optional)" /><label class="flex items-center gap-2 text-sm text-slate-300 md:col-span-2"><input v-model="form.policyAcknowledged" type="checkbox" /> I reviewed the active clinic policies with the client.</label></div>
        <button class="btn mt-4" :disabled="busy || !!createdAppointment" @click="createAppointment">{{ createdAppointment ? 'Appointment created' : 'Create walk-in appointment' }}</button>
      </section>
      <section class="rounded-xl border border-slate-700 bg-slate-800 p-5"><h2 class="text-lg font-semibold">3. POS Payment</h2><p v-if="!createdAppointment" class="mt-2 text-slate-400">Create the appointment before collecting payment.</p>
        <div v-else class="mt-4 grid gap-3 md:grid-cols-2"><div class="rounded-lg bg-slate-900 p-4"><p class="text-sm text-slate-400">Amount due</p><p class="text-2xl font-bold">₱{{ money(createdAppointment.amount) }}</p></div><div><select v-model="payment.method" class="input"><option>Cash</option><option>GCash</option><option>Card</option></select><input v-if="payment.method === 'Cash'" v-model.number="payment.tendered" class="input mt-3" type="number" min="0" step="0.01" placeholder="Cash received" /></div><button class="btn md:col-span-2" :disabled="busy" @click="collectPayment">Collect payment</button></div>
        <div v-if="receipt" class="mt-4 rounded-lg border border-emerald-500/50 bg-emerald-950/30 p-4"><p class="font-semibold">Payment recorded</p><p>{{ receipt.clientName }} · ₱{{ money(receipt.total) }} · {{ receipt.method }}</p><p class="mt-2 text-sm text-slate-300">Service key: <strong class="text-xl tracking-widest text-white">{{ receipt.serviceKey }}</strong></p><button class="btn secondary mt-3" @click="printReceipt">Print receipt</button></div>
      </section>
    </div></main>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { addDoc, collection, getDoc, getDocs, query, serverTimestamp, where, doc } from 'firebase/firestore'
import { auth, db } from '@/config/firebaseConfig'
import OwnerSidebar from '@/components/sidebar/OwnerSidebar.vue'
import { OTP_BACKEND_CANDIDATES } from '@/utils/runtimeConfig'

const branchId = ref(''), busy = ref(false), error = ref(''), clients = ref([]), services = ref([]), practitioners = ref([]), showNewClient = ref(false), createdAppointment = ref(null), receipt = ref(null)
const today = new Date().toISOString().slice(0, 10)
const form = ref({ clientId: '', serviceId: '', practitionerId: '', date: today, time: '', notes: '', policyAcknowledged: false })
const newClient = ref({ firstName: '', lastName: '', phone: '', email: '' })
const payment = ref({ method: 'Cash', tendered: null })
const selectedClient = computed(() => clients.value.find(row => row.id === form.value.clientId))
const selectedService = computed(() => services.value.find(row => row.id === form.value.serviceId))
const selectedPractitioner = computed(() => practitioners.value.find(row => row.id === form.value.practitionerId))
const money = value => Number(value || 0).toFixed(2)
const api = async (path, body) => { const token = await auth.currentUser.getIdToken(); let last; for (const base of OTP_BACKEND_CANDIDATES) { try { const response = await fetch(base + path, { method: 'POST', headers: { 'content-type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Request failed.'); return data } catch (e) { last = e } } throw last }
async function load() { const user = auth.currentUser; if (!user) return; const profile = await getDoc(doc(db, 'users', user.uid)); branchId.value = String(profile.data()?.branchId || ''); if (!branchId.value) throw new Error('Your account has no branch assignment.'); const [clientRows, serviceRows, staffRows] = await Promise.all([getDocs(query(collection(db, 'clients'), where('branchId', '==', branchId.value))), getDocs(query(collection(db, 'productServicePosts'), where('branchId', '==', branchId.value))), getDocs(query(collection(db, 'users'), where('branchId', '==', branchId.value)))]); clients.value = clientRows.docs.map(row => ({ id: row.id, ...row.data() })).filter(row => row.status !== 'Inactive'); services.value = serviceRows.docs.map(row => ({ id: row.id, ...row.data(), name: row.data().serviceName || row.data().name || row.data().title, price: Number(row.data().price || row.data().consultationFee || 0) })).filter(row => String(row.postType || '').toLowerCase() === 'service' && row.name && row.price > 0 && row.isPublished !== false); practitioners.value = staffRows.docs.map(row => ({ id: row.id, ...row.data(), fullName: row.data().fullName || `${row.data().firstName || ''} ${row.data().lastName || ''}`.trim() })).filter(row => String(row.role || row.customRoleName || '').toLowerCase().includes('practitioner') && !row.archived && String(row.status || '').toLowerCase() !== 'inactive') }
async function createClient() { error.value = ''; if (!newClient.value.firstName || !newClient.value.lastName || !newClient.value.phone) return error.value = 'First name, last name, and phone are required.'; busy.value = true; try { const fullName = `${newClient.value.firstName} ${newClient.value.lastName}`.trim(); const ref = await addDoc(collection(db, 'clients'), { ...newClient.value, fullName, branchId: branchId.value, status: 'Active', createdBy: auth.currentUser.uid, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); clients.value.push({ id: ref.id, ...newClient.value, fullName }); form.value.clientId = ref.id; showNewClient.value = false; newClient.value = { firstName: '', lastName: '', phone: '', email: '' } } catch (e) { error.value = e.message || 'Unable to save client.' } finally { busy.value = false } }
async function createAppointment() { error.value = ''; if (!selectedClient.value || !selectedService.value || !selectedPractitioner.value || !form.value.date || !form.value.time) return error.value = 'Select a client, service, practitioner, date, and time.'; busy.value = true; try { const result = await api('/bookings/create', { reservation: { source: 'walk_in', clientId: selectedClient.value.id, customerId: selectedClient.value.id, branchId: branchId.value, customerName: selectedClient.value.fullName, customerEmail: selectedClient.value.email || '', customerPhone: selectedClient.value.phone || '', practitionerId: selectedPractitioner.value.id, practitionerName: selectedPractitioner.value.fullName, selectedServices: [selectedService.value], selectedServiceIds: [selectedService.value.id], service: selectedService.value.name, policyAcknowledged: form.value.policyAcknowledged, date: form.value.date, time: form.value.time, durationMinutes: Number(selectedService.value.durationMinutes || 60), notes: form.value.notes } }); createdAppointment.value = { id: result.data.appointmentId, amount: selectedService.value.price } } catch (e) { error.value = e.message || 'Unable to create walk-in appointment.' } finally { busy.value = false } }
async function collectPayment() { error.value = ''; if (payment.value.method !== 'Cash') return error.value = 'GCash and Card require PayMongo checkout; use Cash here or complete payment through the configured checkout station.'; busy.value = true; try { const result = await api(`/appointments/${createdAppointment.value.id}/walk-in-payment`, { amount: createdAppointment.value.amount, tendered: payment.value.tendered, method: payment.value.method }); receipt.value = result.data } catch (e) { error.value = e.message || 'Unable to record payment.' } finally { busy.value = false } }
function printReceipt() { const content = `Walk-in receipt\n${receipt.value.clientName}\n${receipt.value.service}\nPaid: PHP ${money(receipt.value.total)}\nService key: ${receipt.value.serviceKey}`; const tab = window.open('', '_blank'); if (tab) { tab.document.write(`<pre>${content}</pre>`); tab.print() } }
onMounted(() => load().catch(e => error.value = e.message || 'Unable to load the walk-in desk.'))
</script>

<style scoped>.input{width:100%;border:1px solid #475569;border-radius:.5rem;background:#0f172a;padding:.65rem;color:#fff}.btn{border-radius:.5rem;background:#7c3aed;padding:.65rem 1rem;font-weight:600;color:#fff}.btn:disabled{opacity:.5}.secondary{background:#334155}</style>
