<template>
  <div class="flex min-h-screen bg-slate-900 text-white"><OwnerSidebar />
    <main class="flex-1 p-4 md:p-8"><div class="mx-auto max-w-5xl space-y-6">
      <header><h1 class="text-3xl font-bold">Walk-In Desk</h1><p class="mt-1 text-slate-400">Register a client, schedule their service, then collect payment.</p></header>
      <p v-if="error" class="rounded-lg border border-rose-500/50 bg-rose-950/30 p-3 text-rose-200">{{ error }}</p>
      <section class="rounded-xl border border-slate-700 bg-slate-800 p-5"><h2 class="text-lg font-semibold">1. Client</h2><div class="mt-4 grid gap-3 md:grid-cols-2"><select v-model="form.clientId" class="input"><option value="">Select an existing client</option><option v-for="client in clients" :key="client.id" :value="client.id">{{ client.fullName }} · {{ client.phone || 'No phone' }}</option></select><button class="btn secondary" @click="showNewClient = !showNewClient">{{ showNewClient ? 'Use existing client' : 'Register new client' }}</button></div><div v-if="showNewClient" class="mt-4 grid gap-3 md:grid-cols-2"><input v-model.trim="newClient.firstName" class="input" placeholder="First name" /><input v-model.trim="newClient.lastName" class="input" placeholder="Last name" /><input v-model.trim="newClient.phone" class="input" placeholder="Phone number" /><input v-model.trim="newClient.email" class="input" placeholder="Email (optional)" /><button class="btn md:col-span-2" :disabled="busy" @click="createClient">Save walk-in client</button></div></section>
      <section class="rounded-xl border border-slate-700 bg-slate-800 p-5"><h2 class="text-lg font-semibold">2. Service Schedule</h2><p class="mt-1 text-sm text-slate-400">Select a service, consultation, or package, then use the customer booking calendar to select an available time. {{ availabilityBasis }}</p><div class="mt-4 grid gap-3 md:grid-cols-2"><select v-model="form.serviceId" class="input"><option value="">Select service, consultation, or package</option><option v-for="service in services" :key="service.id" :value="service.id">{{ service.name }} · ₱{{ money(service.price) }}</option></select><select v-model="form.practitionerId" class="input"><option value="">Select practitioner</option><option v-for="person in practitioners" :key="person.id" :value="person.id">{{ person.fullName }}</option></select></div>
        <div v-if="selectedService && selectedPractitioner" class="mt-5 grid gap-4 xl:grid-cols-[minmax(0,1.25fr)_320px]"><div class="rounded-2xl border border-slate-700 bg-slate-900/60 p-4"><div class="mb-4 flex items-center justify-between gap-3"><button type="button" class="calendar-nav" :disabled="!canGoPreviousMonth" @click="changeCalendarMonth(-1)"><Icon icon="mdi:chevron-left" class="h-5 w-5" /></button><p class="font-semibold">{{ calendarMonthLabel }}</p><button type="button" class="calendar-nav" @click="changeCalendarMonth(1)"><Icon icon="mdi:chevron-right" class="h-5 w-5" /></button></div><div class="grid grid-cols-7 gap-2 text-center text-[11px] font-semibold uppercase tracking-wide text-slate-400"><span v-for="day in weekdays" :key="day">{{ day }}</span></div><div class="mt-2 grid grid-cols-7 gap-2"><button v-for="day in calendarDays" :key="day.dateKey" type="button" class="calendar-day" :class="[day.isSelected ? 'selected' : '', day.isAvailable ? 'available' : 'disabled', !day.inCurrentMonth ? 'opacity-50' : '']" :disabled="!day.isAvailable" @click="selectDate(day.dateKey)"><span>{{ day.dayNumber }}</span><span class="calendar-dot"></span></button></div><p class="mt-4 text-xs text-slate-400">{{ selectedDateLabel }}</p></div><div class="rounded-2xl border border-slate-700 bg-slate-900/60 p-4"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Available Time Slots</p><p class="mt-2 text-sm font-semibold">{{ selectedPractitioner.fullName }}</p><div v-if="slotsForSelectedDate.length" class="mt-3 max-h-72 space-y-2 overflow-y-auto pr-1"><button v-for="slot in slotsForSelectedDate" :key="slot.key" type="button" class="slot" :class="form.time === slot.time ? 'selected' : ''" @click="selectSlot(slot)"><span>Starts at {{ minutesToTime12(parseClockToMinutes(slot.time)) }}</span><span class="text-xs text-slate-400">Ends {{ minutesToTime12(parseClockToMinutes(slot.endTime)) }}</span></button></div><p v-else class="mt-3 rounded-xl border border-dashed border-slate-600 p-4 text-sm text-slate-400">Select an available date to see its time slots.</p></div></div>
        <p v-else class="mt-4 rounded-xl border border-dashed border-slate-600 bg-slate-900/40 p-4 text-sm text-slate-400">Choose the offering and practitioner to display available dates and time slots.</p><section v-if="activePolicies.length" class="mt-4 rounded-xl border border-amber-500/35 bg-amber-950/20 p-4"><p class="font-semibold text-amber-100">Applicable clinic policies</p><p class="mt-1 text-xs text-amber-200/80">These configured rules will be saved with this appointment and applied to its transaction.</p><div class="mt-3 space-y-2"><article v-for="policy in activePolicies" :key="policy.key" class="rounded-lg border border-slate-600 bg-slate-900/60 p-3"><p class="text-sm font-semibold">{{ policy.label }}</p><p class="mt-1 text-xs leading-5 text-slate-300">{{ policy.text }}</p></article></div></section><div class="mt-4 grid gap-3 md:grid-cols-2"><textarea v-model.trim="form.notes" class="input md:col-span-2" rows="2" placeholder="Notes (optional)" /><label class="flex items-center gap-2 text-sm text-slate-300 md:col-span-2"><input v-model="form.policyAcknowledged" type="checkbox" /> I reviewed the active clinic policies with the client.</label></div><button class="btn mt-4" :disabled="busy || !!createdAppointment" @click="createAppointment">{{ createdAppointment ? 'Appointment created' : 'Create walk-in appointment' }}</button>
      </section>
      <section class="rounded-xl border border-slate-700 bg-slate-800 p-5"><h2 class="text-lg font-semibold">3. Payment</h2><p v-if="!createdAppointment" class="mt-2 text-slate-400">Create the appointment before collecting payment.</p><div v-else class="mt-4 grid gap-3 md:grid-cols-2"><div class="rounded-lg bg-slate-900 p-4"><p class="text-sm text-slate-400">Amount due</p><p class="text-2xl font-bold">₱{{ money(createdAppointment.amount) }}</p></div><div><select v-model="payment.method" class="input"><option>Cash</option><option>GCash</option><option>Card</option></select><input v-if="payment.method === 'Cash'" v-model.number="payment.tendered" class="input mt-3" type="number" min="0" step="0.01" placeholder="Cash received" /></div><button class="btn md:col-span-2" :disabled="busy" @click="collectPayment">Collect payment</button></div><div v-if="receipt" class="mt-4 rounded-lg border border-emerald-500/50 bg-emerald-950/30 p-4"><p class="font-semibold">Payment recorded</p><p>{{ receipt.clientName }} · ₱{{ money(receipt.total) }} · {{ receipt.method }}</p><p class="mt-2 text-sm text-slate-300">Service key: <strong class="text-xl tracking-widest text-white">{{ receipt.serviceKey }}</strong></p><button class="btn secondary mt-3" @click="printReceipt">Print receipt</button></div></section>
    </div></main>
  </div>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { addDoc, collection, doc, getDoc, getDocs, query, serverTimestamp, where } from 'firebase/firestore'
import { Icon } from '@iconify/vue'
import { auth, db } from '@/config/firebaseConfig'
import OwnerSidebar from '@/components/sidebar/OwnerSidebar.vue'
import { OTP_BACKEND_CANDIDATES } from '@/utils/runtimeConfig'
import { buildWeekScheduleMap, getScheduleDayWindow } from '@/utils/employeeSchedules'

const branchId = ref(''), busy = ref(false), error = ref(''), clients = ref([]), services = ref([]), practitioners = ref([]), practitionerSchedules = ref({}), practitionerLeaves = ref({}), operatingHours = ref({}), planTier = ref('basic'), activePolicies = ref([]), showNewClient = ref(false), createdAppointment = ref(null), receipt = ref(null)
const form = ref({ clientId: '', serviceId: '', practitionerId: '', date: '', time: '', notes: '', policyAcknowledged: false })
const newClient = ref({ firstName: '', lastName: '', phone: '', email: '' })
const payment = ref({ method: 'Cash', tendered: null })
const selectedClient = computed(() => clients.value.find(row => row.id === form.value.clientId))
const selectedService = computed(() => services.value.find(row => row.id === form.value.serviceId))
const selectedPractitioner = computed(() => practitioners.value.find(row => row.id === form.value.practitionerId))
const money = value => Number(value || 0).toFixed(2)
const weekdays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
const calendarMonth = ref(new Date(new Date().getFullYear(), new Date().getMonth(), 1))
const isPremiumPlan = computed(() => planTier.value === 'premium')
const availabilityBasis = computed(() => isPremiumPlan.value ? 'Premium availability follows the selected practitioner’s daily shift.' : 'Basic availability follows this clinic’s operating hours.')
const api = async (path, body) => { const token = await auth.currentUser.getIdToken(); let last; for (const base of OTP_BACKEND_CANDIDATES) { try { const response = await fetch(base + path, { method: 'POST', headers: { 'content-type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Request failed.'); return data } catch (e) { last = e } } throw last }
const apiGet = async path => { const token = await auth.currentUser.getIdToken(); let last; for (const base of OTP_BACKEND_CANDIDATES) { try { const response = await fetch(base + path, { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Request failed.'); return data } catch (e) { last = e } } throw last }
const toDateKey = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const parseDate = value => { const [year, month, day] = String(value || '').split('-').map(Number); return year && month && day ? new Date(year, month - 1, day) : null }
const parseClockToMinutes = value => { const match = String(value || '').trim().match(/^(\d{1,2}):(\d{2})$/); if (!match) return null; const hours = Number(match[1]), minutes = Number(match[2]); return hours >= 0 && hours < 24 && minutes >= 0 && minutes < 60 ? hours * 60 + minutes : null }
const minutesToTime = value => `${String(Math.floor(value / 60) % 24).padStart(2, '0')}:${String(value % 60).padStart(2, '0')}`
const minutesToTime12 = value => { if (!Number.isFinite(value)) return ''; const hour = Math.floor(value / 60) % 24; return `${hour % 12 || 12}:${String(value % 60).padStart(2, '0')} ${hour >= 12 ? 'PM' : 'AM'}` }
const weekStart = date => { const result = new Date(date); result.setDate(result.getDate() - ((result.getDay() + 6) % 7)); return toDateKey(result) }
const shiftWindow = label => { const [startRaw, endRaw] = String(label || '').split('-').map(part => part.trim()); const start = parseClockToMinutes(startRaw), end = parseClockToMinutes(endRaw); return start === null || end === null ? null : { start, end } }
const isOnLeave = (id, dateKey) => (practitionerLeaves.value?.[id] || []).some(leave => leave.startDate <= dateKey && dateKey <= leave.endDate)
const appointmentSlots = computed(() => { if (!selectedService.value || !selectedPractitioner.value) return []; const slots = [], duration = Math.max(30, Number(selectedService.value.durationMinutes || 60)), current = new Date(), currentKey = toDateKey(current), now = current.getHours() * 60 + current.getMinutes(); for (let offset = 0; offset < 365; offset += 1) { const date = new Date(current); date.setDate(current.getDate() + offset); const dateKey = toDateKey(date); const weekday = date.toLocaleDateString('en-US', { weekday: 'long' }); if (isPremiumPlan.value && isOnLeave(selectedPractitioner.value.id, dateKey)) continue; const window = isPremiumPlan.value ? getScheduleDayWindow(practitionerSchedules.value[selectedPractitioner.value.id] || {}, weekStart(date), weekday) : operatingHours.value[weekday.toLowerCase()]; const period = window && window.closed !== true && shiftWindow(`${window.start || window.open} - ${window.end || window.close}`); if (!period) continue; let { start, end } = period; if (end < start) end += 1440; if (dateKey === currentKey) start = Math.max(start, now + 30); for (let value = start; value + duration <= end; value += 30) { const normalized = value % 1440; slots.push({ key: `${dateKey}|${normalized}`, date: dateKey, time: minutesToTime(normalized), endTime: minutesToTime((normalized + duration) % 1440) }) } } return slots })
const availableDateSet = computed(() => new Set(appointmentSlots.value.map(slot => slot.date)))
const calendarMonthLabel = computed(() => calendarMonth.value.toLocaleDateString('en-US', { month: 'long', year: 'numeric' }))
const canGoPreviousMonth = computed(() => calendarMonth.value.getFullYear() > new Date().getFullYear() || calendarMonth.value.getMonth() > new Date().getMonth())
const calendarDays = computed(() => { const first = new Date(calendarMonth.value.getFullYear(), calendarMonth.value.getMonth(), 1), start = new Date(first); start.setDate(1 - first.getDay()); return Array.from({ length: 42 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); const dateKey = toDateKey(date); return { dateKey, dayNumber: date.getDate(), inCurrentMonth: date.getMonth() === calendarMonth.value.getMonth(), isAvailable: availableDateSet.value.has(dateKey), isSelected: form.value.date === dateKey } }) })
const slotsForSelectedDate = computed(() => appointmentSlots.value.filter(slot => slot.date === form.value.date))
const selectedDateLabel = computed(() => { const date = parseDate(form.value.date); return date ? date.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }) : 'Choose an available date from the calendar.' })
const changeCalendarMonth = direction => { const next = new Date(calendarMonth.value); next.setMonth(next.getMonth() + direction); if (direction > 0 || canGoPreviousMonth.value) calendarMonth.value = next }
const selectDate = date => { form.value.date = date; form.value.time = '' }
const selectSlot = slot => { form.value.time = slot.time }
watch([() => form.value.serviceId, () => form.value.practitionerId], () => { form.value.date = ''; form.value.time = ''; calendarMonth.value = new Date(new Date().getFullYear(), new Date().getMonth(), 1) })
async function load() { const user = auth.currentUser; if (!user) return; const profile = await getDoc(doc(db, 'users', user.uid)); branchId.value = String(profile.data()?.branchId || ''); if (!branchId.value) throw new Error('Your account has no branch assignment.'); const [clinicSnap, policySnap, clientRows, serviceRows, availability] = await Promise.all([getDoc(doc(db, 'clinics', branchId.value)), getDoc(doc(db, 'clinicPolicies', branchId.value)), getDocs(query(collection(db, 'clients'), where('branchId', '==', branchId.value))), getDocs(query(collection(db, 'productServicePosts'), where('branchId', '==', branchId.value))), apiGet(`/public/clinics/${encodeURIComponent(branchId.value)}/practitioners`)]); const clinic = clinicSnap.exists() ? clinicSnap.data() || {} : {}, policyData = policySnap.exists() ? policySnap.data() || {} : {}; planTier.value = String(clinic.subscriptionPlan || profile.data()?.subscriptionPlan || 'basic').trim().toLowerCase() === 'premium' ? 'premium' : 'basic'; operatingHours.value = clinic.operatingHours && typeof clinic.operatingHours === 'object' ? clinic.operatingHours : {}; activePolicies.value = [['paymentPolicy', 'Payment Policy'], ['cancellationPolicy', 'Cancellation Policy'], ['reschedulePolicy', 'Rescheduling Policy'], ['noShowPolicy', 'No-Show Policy'], ['walkInPolicy', 'Walk-In Policy']].filter(([key]) => policyData[`${key}Enabled`] === true && String(policyData[key] || '').trim()).map(([key, label]) => ({ key, label, text: String(policyData[key]).trim() })); clients.value = clientRows.docs.map(row => ({ id: row.id, ...row.data() })).filter(row => row.status !== 'Inactive'); services.value = serviceRows.docs.map(row => ({ id: row.id, ...row.data(), name: row.data().serviceName || row.data().consultationName || row.data().packageName || row.data().name || row.data().title, price: Number(row.data().price || row.data().consultationFee || 0), durationMinutes: Number(row.data().durationMinutes || 60) })).filter(row => ['service', 'consultation', 'package'].includes(String(row.postType || '').toLowerCase()) && row.name && row.price > 0 && row.isPublished !== false && row.archived !== true); practitioners.value = Array.isArray(availability.practitioners) ? availability.practitioners : []; practitionerSchedules.value = Object.fromEntries(Object.entries(availability.schedules || {}).map(([id, schedules]) => [id, buildWeekScheduleMap(Array.isArray(schedules) ? schedules : [])])); practitionerLeaves.value = availability.leaves || {} }
async function createClient() { error.value = ''; if (!newClient.value.firstName || !newClient.value.lastName || !newClient.value.phone) return error.value = 'First name, last name, and phone are required.'; busy.value = true; try { const fullName = `${newClient.value.firstName} ${newClient.value.lastName}`.trim(); const clientRef = await addDoc(collection(db, 'clients'), { ...newClient.value, fullName, branchId: branchId.value, status: 'Active', createdBy: auth.currentUser.uid, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); clients.value.push({ id: clientRef.id, ...newClient.value, fullName }); form.value.clientId = clientRef.id; showNewClient.value = false; newClient.value = { firstName: '', lastName: '', phone: '', email: '' } } catch (e) { error.value = e.message || 'Unable to save client.' } finally { busy.value = false } }
async function createAppointment() { error.value = ''; if (!selectedClient.value || !selectedService.value || !selectedPractitioner.value || !form.value.date || !form.value.time) return error.value = 'Select a client, offering, practitioner, date, and available time.'; if (activePolicies.value.length && !form.value.policyAcknowledged) return error.value = 'Review and acknowledge the active clinic policies before continuing.'; busy.value = true; try { const result = await api('/bookings/create', { reservation: { source: 'walk_in', clientId: selectedClient.value.id, customerId: selectedClient.value.id, branchId: branchId.value, customerName: selectedClient.value.fullName, customerEmail: selectedClient.value.email || '', customerPhone: selectedClient.value.phone || '', practitionerId: selectedPractitioner.value.id, practitionerName: selectedPractitioner.value.fullName, selectedServices: [selectedService.value], selectedServiceIds: [selectedService.value.id], service: selectedService.value.name, policyAcknowledged: form.value.policyAcknowledged, date: form.value.date, time: form.value.time, durationMinutes: Number(selectedService.value.durationMinutes || 60), notes: form.value.notes } }); createdAppointment.value = { id: result.data.appointmentId, amount: selectedService.value.price } } catch (e) { error.value = e.message || 'Unable to create walk-in appointment.' } finally { busy.value = false } }
async function collectPayment() { error.value = ''; if (payment.value.method !== 'Cash') return error.value = 'GCash and Card require PayMongo checkout; use Cash here or complete payment through the configured checkout station.'; busy.value = true; try { const result = await api(`/appointments/${createdAppointment.value.id}/walk-in-payment`, { amount: createdAppointment.value.amount, tendered: payment.value.tendered, method: payment.value.method }); receipt.value = result.data } catch (e) { error.value = e.message || 'Unable to record payment.' } finally { busy.value = false } }
function printReceipt() { const content = `Walk-in receipt\n${receipt.value.clientName}\n${receipt.value.service}\nPaid: PHP ${money(receipt.value.total)}\nService key: ${receipt.value.serviceKey}`; const tab = window.open('', '_blank'); if (tab) { tab.document.write(`<pre>${content}</pre>`); tab.print() } }
onMounted(() => load().catch(e => error.value = e.message || 'Unable to load the walk-in desk.'))
</script>

<style scoped>
.input{width:100%;border:1px solid #475569;border-radius:.5rem;background:#0f172a;padding:.65rem;color:#fff}.btn{border-radius:.5rem;background:#7c3aed;padding:.65rem 1rem;font-weight:600;color:#fff}.btn:disabled{cursor:not-allowed;opacity:.5}.secondary{background:#334155}.calendar-nav{display:inline-flex;height:2.25rem;width:2.25rem;align-items:center;justify-content:center;border:1px solid #475569;border-radius:9999px;color:#e2e8f0}.calendar-nav:hover:not(:disabled){background:#334155}.calendar-nav:disabled{opacity:.4}.calendar-day{display:flex;aspect-ratio:1;flex-direction:column;align-items:center;justify-content:space-between;border:1px solid #334155;border-radius:.75rem;padding:.45rem;font-size:.875rem}.calendar-day.available{border-color:#14b8a6;background:#134e4a;color:#ccfbf1}.calendar-day.available:hover{background:#0f766e}.calendar-day.disabled{cursor:not-allowed;color:#64748b}.calendar-day.selected{border-color:#a78bfa;background:#6d28d9;color:#fff;box-shadow:0 8px 18px rgb(76 29 149 / .35)}.calendar-dot{height:.32rem;width:.32rem;border-radius:9999px;background:currentColor}.slot{display:flex;width:100%;flex-direction:column;gap:.2rem;border:1px solid #475569;border-radius:.75rem;padding:.7rem;text-align:left;font-size:.875rem;transition:.15s}.slot:hover{border-color:#a78bfa;background:#312e81}.slot.selected{border-color:#a78bfa;background:#4c1d95;color:#fff}
</style>
