<template>
  <div class="walk-in-desk flex min-h-screen"><OwnerSidebar /><main class="flex-1 p-4 md:p-8"><div class="mx-auto max-w-5xl space-y-6">
    <header><h1 class="text-3xl font-bold">Walk-In Desk</h1><p class="muted">Register a client, schedule their service, then collect payment.</p></header>
    <p v-if="error" class="error">{{ error }}</p>
    <section class="card"><h2 class="text-lg font-semibold">1. Client</h2><div class="mt-4 grid gap-3 md:grid-cols-2"><select v-model="form.clientId" class="input"><option value="">Select an existing client</option><option v-for="client in clients" :key="client.id" :value="client.id">{{ client.fullName }} · {{ client.phone || 'No phone' }}</option></select><button class="btn secondary" @click="showNewClient=!showNewClient">{{ showNewClient ? 'Use existing client' : 'Register new client' }}</button></div><p class="mt-3 text-sm text-[#e2c7b6]">An email address is required. We send the booking details and service key there. The practitioner verifies the service key on the appointment day.</p><div v-if="showNewClient" class="mt-4 grid gap-3 md:grid-cols-2"><input v-model.trim="newClient.firstName" class="input" placeholder="First name"><input v-model.trim="newClient.lastName" class="input" placeholder="Last name"><div><label class="phone"><span>+63</span><input v-model="newClient.phone" inputmode="numeric" maxlength="10" placeholder="9XXXXXXXXX" aria-label="Phone number" @input="normalizePhone"></label><p v-if="phoneError" class="field-error">{{ phoneError }}</p></div><input v-model.trim="newClient.email" class="input" type="email" required placeholder="Email address *"><button class="btn md:col-span-2" :disabled="busy" @click="createClient">Save walk-in client</button></div></section>
    <section class="card"><h2 class="text-lg font-semibold">2. Service Schedule</h2><p class="muted">Select an offering, practitioner, date, and available time.</p><div class="mt-4 grid gap-3 md:grid-cols-2"><select v-model="form.serviceId" class="input"><option value="">Select service, consultation, or package</option><option v-for="service in services" :key="service.id" :value="service.id">{{ service.name }} · ₱{{ money(service.price) }}</option></select><select v-model="form.practitionerId" class="input"><option value="">Select practitioner</option><option v-for="person in practitioners" :key="person.id" :value="person.id">{{ person.fullName }}</option></select><input v-model="form.date" class="input" type="date" :min="today"><select v-model="form.time" class="input" :disabled="!form.date || !selectedPractitioner"><option value="">Select available time</option><option v-for="slot in slots" :key="slot" :value="slot">{{ slot }}</option></select></div><textarea v-model.trim="form.notes" class="input mt-3" rows="2" placeholder="Notes (optional)"></textarea><button class="btn mt-4" :disabled="busy || !!createdAppointment" @click="createAppointment">{{ createdAppointment ? 'Appointment created' : 'Create walk-in appointment' }}</button></section>
    <section class="card"><h2 class="text-lg font-semibold">3. Payment</h2><p v-if="!createdAppointment" class="muted">Create the appointment before collecting payment.</p><div v-else class="mt-4 grid gap-3 md:grid-cols-2"><div class="amount"><p class="muted">Amount due</p><p class="text-2xl font-bold">₱{{ money(createdAppointment.amount) }}</p></div><div><select v-model="payment.method" class="input"><option>Cash</option><option>GCash</option><option>Card</option></select><input v-if="payment.method==='Cash'" v-model.number="payment.tendered" class="input mt-3" type="number" min="0" step="0.01" placeholder="Cash received"></div><button class="btn md:col-span-2" :disabled="busy" @click="collectPayment">Collect payment</button></div><div v-if="receipt" class="receipt"><p class="font-semibold">Payment recorded</p><p>{{ receipt.clientName }} · ₱{{ money(receipt.total) }} · {{ receipt.method }}</p><p>Service key: <strong>{{ receipt.serviceKey }}</strong></p><button class="btn secondary mt-3" @click="printReceipt">Print receipt</button></div></section>
  </div></main></div>
</template>
<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { addDoc, collection, doc, getDoc, getDocs, query, serverTimestamp, where } from 'firebase/firestore'
import { auth, db } from '@/config/firebaseConfig'
import OwnerSidebar from '@/components/sidebar/OwnerSidebar.vue'
import { OTP_BACKEND_CANDIDATES } from '@/utils/runtimeConfig'
import { buildWeekScheduleMap, getScheduleDayWindow } from '@/utils/employeeSchedules'

const branchId=ref(''), busy=ref(false), error=ref(''), clients=ref([]), services=ref([]), practitioners=ref([]), practitionerSchedules=ref({}), practitionerLeaves=ref({}), operatingHours=ref({}), planTier=ref('basic'), showNewClient=ref(false), createdAppointment=ref(null), receipt=ref(null), phoneError=ref('')
const form=ref({clientId:'',serviceId:'',practitionerId:'',date:'',time:'',notes:''}), newClient=ref({firstName:'',lastName:'',phone:'',email:''}), payment=ref({method:'Cash',tendered:null})
const selectedClient=computed(()=>clients.value.find(row=>row.id===form.value.clientId)), selectedService=computed(()=>services.value.find(row=>row.id===form.value.serviceId)), selectedPractitioner=computed(()=>practitioners.value.find(row=>row.id===form.value.practitionerId))
const money=value=>Number(value||0).toFixed(2), today=new Date().toISOString().slice(0,10)
const isPremiumPlan=computed(()=>planTier.value==='premium')
const slots=computed(()=>{if(!form.value.date||!selectedPractitioner.value)return [];const selectedDate=new Date(`${form.value.date}T00:00:00`),weekday=selectedDate.toLocaleDateString('en-US',{weekday:'long'}),weekStartDate=new Date(selectedDate);weekStartDate.setDate(selectedDate.getDate()-((selectedDate.getDay()+6)%7));const weekKey=`${weekStartDate.getFullYear()}-${String(weekStartDate.getMonth()+1).padStart(2,'0')}-${String(weekStartDate.getDate()).padStart(2,'0')}`,leave=(practitionerLeaves.value[selectedPractitioner.value.id]||[]).some(row=>row.startDate<=form.value.date&&form.value.date<=row.endDate);if(leave)return [];const window=isPremiumPlan.value?getScheduleDayWindow(practitionerSchedules.value[selectedPractitioner.value.id]||{},weekKey,weekday):operatingHours.value[weekday.toLowerCase()];const startText=window?.start||window?.open,endText=window?.end||window?.close;if(!window||window.closed===true||!startText||!endText)return [];const parse=value=>{const match=String(value).match(/^(\d{1,2}):(\d{2})$/);return match?Number(match[1])*60+Number(match[2]):null},start=parse(startText),end=parse(endText),duration=Math.max(30,Number(selectedService.value?.durationMinutes||60));if(start===null||end===null||end<=start)return [];const result=[];for(let minute=start;minute+duration<=end;minute+=30)result.push(`${String(Math.floor(minute/60)).padStart(2,'0')}:${String(minute%60).padStart(2,'0')}`);return result})
const normalizePhone=()=>{let digits=String(newClient.value.phone||'').replace(/\D/g,'');if(digits.startsWith('63'))digits=digits.slice(2);if(digits.startsWith('0'))digits=digits.slice(1);newClient.value.phone=digits.slice(0,10);phoneError.value=digits&&!/^9\d{9}$/.test(newClient.value.phone)?'Enter exactly 10 digits beginning with 9.':''}
const validPhone=()=>{normalizePhone();return /^9\d{9}$/.test(newClient.value.phone)}
const api=async(path,body)=>{const token=await auth.currentUser.getIdToken();let last;for(const base of OTP_BACKEND_CANDIDATES){try{const response=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)}),data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'Request failed.');return data}catch(cause){last=cause}}throw last}
const apiGet=async path=>{const token=await auth.currentUser.getIdToken();let last;for(const base of OTP_BACKEND_CANDIDATES){try{const response=await fetch(base+path,{headers:{Authorization:`Bearer ${token}`}}),data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'Request failed.');return data}catch(cause){last=cause}}throw last}
watch([()=>form.value.serviceId,()=>form.value.practitionerId,()=>form.value.date],()=>{form.value.time=''})
async function load(){const user=auth.currentUser;if(!user)return;const profile=await getDoc(doc(db,'users',user.uid));branchId.value=String(profile.data()?.branchId||'');if(!branchId.value)throw Error('Your account has no branch assignment.');const [clinicSnap,clientRows,serviceRows,availability]=await Promise.all([getDoc(doc(db,'clinics',branchId.value)),getDocs(query(collection(db,'clients'),where('branchId','==',branchId.value))),getDocs(query(collection(db,'productServicePosts'),where('branchId','==',branchId.value))),apiGet(`/public/clinics/${encodeURIComponent(branchId.value)}/practitioners`)]);const clinic=clinicSnap.exists()?clinicSnap.data()||{}:{};planTier.value=String(clinic.subscriptionPlan||profile.data()?.subscriptionPlan||'basic').trim().toLowerCase()==='premium'?'premium':'basic';operatingHours.value=clinic.operatingHours&&typeof clinic.operatingHours==='object'?clinic.operatingHours:{};clients.value=clientRows.docs.map(row=>({id:row.id,...row.data()})).filter(row=>row.status!=='Inactive');services.value=serviceRows.docs.map(row=>({id:row.id,...row.data(),name:row.data().serviceName||row.data().consultationName||row.data().packageName||row.data().name||row.data().title,price:Number(row.data().price||row.data().consultationFee||0),durationMinutes:Number(row.data().durationMinutes||60)})).filter(row=>['service','consultation','package'].includes(String(row.postType||'').toLowerCase())&&row.name&&row.price>0&&row.isPublished!==false&&row.archived!==true);practitioners.value=Array.isArray(availability.practitioners)?availability.practitioners:[];practitionerSchedules.value=Object.fromEntries(Object.entries(availability.schedules||{}).map(([id,rows])=>[id,buildWeekScheduleMap(Array.isArray(rows)?rows:[])]));practitionerLeaves.value=availability.leaves||{}}
async function createClient(){error.value='';const email=String(newClient.value.email||'').trim().toLowerCase();if(!newClient.value.firstName||!newClient.value.lastName||!validPhone()||!/^\S+@\S+\.\S+$/.test(email)){if(!phoneError.value)phoneError.value='Enter exactly 10 digits beginning with 9.';error.value='First name, last name, a valid Philippine mobile number, and a valid email address are required.';return}busy.value=true;try{const fullName=`${newClient.value.firstName} ${newClient.value.lastName}`.trim(),client={...newClient.value,email,phone:`+63${newClient.value.phone}`,fullName,branchId:branchId.value,status:'Active',createdBy:auth.currentUser.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()},clientRef=await addDoc(collection(db,'clients'),client);clients.value.push({id:clientRef.id,...client});form.value.clientId=clientRef.id;showNewClient.value=false;newClient.value={firstName:'',lastName:'',phone:'',email:''};phoneError.value=''}catch(cause){error.value=cause.message||'Unable to save client.'}finally{busy.value=false}}
async function createAppointment(){error.value='';if(!selectedClient.value||!selectedService.value||!selectedPractitioner.value||!form.value.date||!form.value.time)return error.value='Select a client, offering, practitioner, date, and available time.';if(!/^\S+@\S+\.\S+$/.test(String(selectedClient.value.email||'').trim()))return error.value='This walk-in client needs a valid email address before an appointment can be created. The booking details and service key will be sent there.';busy.value=true;try{const result=await api('/bookings/create',{reservation:{source:'walk_in',clientId:selectedClient.value.id,customerId:selectedClient.value.id,branchId:branchId.value,customerName:selectedClient.value.fullName,customerEmail:selectedClient.value.email,customerPhone:selectedClient.value.phone||'',practitionerId:selectedPractitioner.value.id,practitionerName:selectedPractitioner.value.fullName,selectedServices:[selectedService.value],selectedServiceIds:[selectedService.value.id],service:selectedService.value.name,date:form.value.date,time:form.value.time,durationMinutes:Number(selectedService.value.durationMinutes||60),notes:form.value.notes}});createdAppointment.value={id:result.data.appointmentId,amount:selectedService.value.price}}catch(cause){error.value=cause.message||'Unable to create walk-in appointment.'}finally{busy.value=false}}
async function collectPayment(){error.value='';if(payment.value.method!=='Cash')return error.value='GCash and Card require PayMongo checkout; use Cash here or complete payment through the configured checkout station.';busy.value=true;try{const result=await api(`/appointments/${createdAppointment.value.id}/walk-in-payment`,{amount:createdAppointment.value.amount,tendered:payment.value.tendered,method:payment.value.method});receipt.value=result.data}catch(cause){error.value=cause.message||'Unable to record payment.'}finally{busy.value=false}}
function printReceipt(){const content=`Walk-in receipt\n${receipt.value.clientName}\n${receipt.value.service}\nPaid: PHP ${money(receipt.value.total)}\nService key: ${receipt.value.serviceKey}`,tab=window.open('','_blank');if(tab){tab.document.write(`<pre>${content}</pre>`);tab.print()}}
onMounted(()=>load().catch(cause=>error.value=cause.message||'Unable to load the walk-in desk.'))
</script>
<style scoped>
.walk-in-desk{background:#160b06;color:#f7e5d4}.card{border:1px solid #6b3d24;border-radius:1rem;background:#28150b;padding:1.25rem}.muted{margin-top:.25rem;color:#c9ab91}.error{border:1px solid #a95844;border-radius:.7rem;background:#3b1710;padding:.75rem;color:#ffd7ca}.input{width:100%;border:1px solid #754727;border-radius:.55rem;background:#170d09;padding:.65rem .75rem;color:#f9e9da}.input:focus,.phone:focus-within{outline:2px solid #d5a36d;outline-offset:1px}.input::placeholder{color:#b79b86}.btn{border-radius:.55rem;background:#d29b63;padding:.65rem 1rem;font-weight:700;color:#271208}.btn:hover:not(:disabled){background:#e6b47f}.btn:disabled{cursor:not-allowed;opacity:.5}.secondary{border:1px solid #8b5b36;background:#422313;color:#f7e5d4}.phone{display:flex;align-items:center;overflow:hidden;border:1px solid #754727;border-radius:.55rem;background:#170d09;color:#f6d9bd}.phone span{padding:.65rem .7rem;border-right:1px solid #754727;background:#30180c;font-weight:700}.phone input{min-width:0;flex:1;background:transparent;padding:.65rem .75rem;color:#f9e9da;outline:0}.field-error{margin:.35rem 0 0;color:#f3ad98;font-size:.75rem}.amount,.receipt{border:1px solid #6b4324;border-radius:.65rem;background:#211108;padding:1rem}.receipt{margin-top:1rem;border-color:#788c4f;background:#263016;color:#e2f1ca}
</style>
