<template>
  <div class="module-theme flex min-h-screen bg-slate-900 text-slate-100"><OwnerSidebar />
    <main class="min-w-0 flex-1 p-4 md:p-8"><div class="mx-auto max-w-6xl">
      <header class="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[.2em] text-amber-300">Finance</p><h1 class="mt-2 text-3xl font-bold">Expenses &amp; Payments</h1><p class="mt-2 text-sm text-slate-400">Review supplier payables and record authorized operating expenses.</p></div><button v-if="canCreate" class="rounded-lg border border-amber-500 bg-amber-800 px-4 py-2 text-sm" @click="showForm = true">Add operating expense</button></header>
      <p v-if="error" class="mb-4 rounded border border-red-600 bg-red-950/30 p-3 text-sm text-red-200">{{ error }}</p><p v-if="loading" class="text-slate-400">Loading financial records…</p>
      <template v-else><div class="mb-5 flex gap-2 border-b border-slate-700"><button v-for="tab in tabs" :key="tab.key" class="border-0 border-b-2 px-4 py-3 text-sm" :class="tab.key === activeTab ? 'border-amber-400 text-amber-300' : 'border-transparent text-slate-400'" @click="activeTab = tab.key">{{ tab.label }}</button></div>
        <section v-if="activeTab === 'supplier'" class="rounded-xl border border-slate-700 bg-slate-800 p-5"><h2 class="text-lg font-semibold">Supplier invoices</h2><p class="mt-2 text-sm text-slate-400">Invoice verification, three-way matching, and supplier payment recording remain in the procurement invoice workflow.</p><RouterLink to="/finance/procurement/invoices" class="mt-4 inline-block rounded-lg border border-sky-600 bg-sky-900/40 px-4 py-2 text-sm text-sky-100">Open supplier invoices &amp; payments</RouterLink></section>
        <template v-else><div class="mb-5 grid gap-3 sm:grid-cols-3"><article v-for="card in cards" :key="card.label" class="rounded-xl border border-slate-700 bg-slate-800 p-4"><p class="text-sm text-slate-400">{{ card.label }}</p><strong class="mt-2 block text-xl">{{ money(card.value) }}</strong></article></div><div class="mb-4 grid gap-3 sm:grid-cols-3"><select v-model="branchId"><option value="all">All Assigned Branches</option><option v-for="branch in branches" :key="branch.id" :value="branch.id">{{ branch.name }}</option></select><select v-model="status"><option value="">All payment statuses</option><option>Unpaid</option><option>Partially Paid</option><option>Paid</option></select><input v-model="search" placeholder="Search expenses or payees" /></div><section class="overflow-x-auto rounded-xl border border-slate-700"><table class="w-full text-left text-sm"><thead class="bg-slate-800 text-slate-300"><tr><th>Expense</th><th>Branch</th><th>Date</th><th>Amount</th><th>Outstanding</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="record in filtered" :key="record.id" class="border-t border-slate-700"><td><strong>{{ record.category }}</strong><small class="block text-slate-400">{{ record.description }}{{ record.payee ? ' · ' + record.payee : '' }}</small></td><td>{{ branchName(record.branchId) }}</td><td>{{ record.expenseDate || '—' }}</td><td>{{ money(record.amount) }}</td><td>{{ money(record.outstandingAmount) }}</td><td>{{ record.status }}</td><td><button v-if="record.status !== 'Paid' && canSettle" class="rounded border border-slate-600 px-3 py-1 text-xs" @click="openPayment(record)">Record payment</button></td></tr><tr v-if="!filtered.length"><td colspan="7" class="p-8 text-center text-slate-400">No operating expenses match the selected filters.</td></tr></tbody></table></section></template>
      </template>
      <form v-if="showForm" class="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-3" @submit.prevent="create"><section class="w-full max-w-lg rounded-xl border border-slate-700 bg-slate-900 p-6"><h2 class="text-lg font-semibold">Operating expense</h2><div class="mt-4 grid gap-3"><label>Branch<select v-model="draft.branchId" required><option value="">Select branch</option><option v-for="branch in branches" :key="branch.id" :value="branch.id">{{ branch.name }}</option></select></label><label>Category<input v-model.trim="draft.category" required placeholder="Rent, utilities, maintenance…" /></label><label>Description<input v-model.trim="draft.description" required /></label><label>Payee <input v-model.trim="draft.payee" /></label><label>Amount (PHP)<input v-model.number="draft.amount" type="number" min="0.01" step="0.01" required /></label><label>Expense date<input v-model="draft.expenseDate" type="date" required /></label><label>Due date<input v-model="draft.dueDate" type="date" /></label><label>Notes<textarea v-model.trim="draft.notes" rows="2" /></label></div><div class="mt-5 flex justify-end gap-2"><button type="button" @click="showForm=false">Cancel</button><button class="bg-amber-800" :disabled="saving">Save expense</button></div></section></form>
      <form v-if="paymentTarget" class="fixed inset-0 z-[60] flex items-center justify-center bg-black/75 p-3" @submit.prevent="recordPayment"><section class="w-full max-w-md rounded-xl border border-slate-700 bg-slate-900 p-6"><h2 class="text-lg font-semibold">Record expense payment</h2><p class="mt-1 text-sm text-slate-400">Outstanding: {{ money(paymentTarget.outstandingAmount) }}</p><div class="mt-4 grid gap-3"><label>Amount (PHP)<input v-model.number="payment.amount" type="number" min="0.01" :max="paymentTarget.outstandingAmount / 100" step="0.01" required /></label><label>Method<input v-model.trim="payment.paymentMethod" required /></label><label>Reference<input v-model.trim="payment.paymentReference" required /></label></div><div class="mt-5 flex justify-end gap-2"><button type="button" @click="paymentTarget=null">Cancel</button><button class="bg-amber-800" :disabled="saving">Record payment</button></div></section></form>
    </div></main>
  </div>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import OwnerSidebar from '@/components/sidebar/OwnerSidebar.vue'
import { auth } from '@/config/firebaseConfig'
import { OTP_BACKEND_CANDIDATES } from '@/utils/runtimeConfig'
const activeTab=ref('supplier'), loading=ref(true), saving=ref(false), error=ref(''), records=ref([]), branches=ref([]), branchId=ref('all'), status=ref(''), search=ref(''), permissions=ref([]), showForm=ref(false), paymentTarget=ref(null)
const blank=()=>({branchId:'',category:'',description:'',payee:'',amount:'',expenseDate:new Date().toISOString().slice(0,10),dueDate:'',notes:''}); const draft=ref(blank()), payment=ref({amount:'',paymentMethod:'',paymentReference:''})
const canCreate=computed(()=>permissions.value.includes('finance:payables:approve')||permissions.value.includes('administrator:full_access'));const canSettle=computed(()=>permissions.value.includes('finance:payables:settle')||permissions.value.includes('administrator:full_access'));const tabs=[{key:'supplier',label:'Supplier Invoices'},{key:'other',label:'Other Expenses'}]
const money=value=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(value||0)/100);const branchName=id=>branches.value.find(branch=>branch.id===id)?.name||id
const filtered=computed(()=>records.value.filter(record=>record.kind==='operatingExpense'&&(branchId.value==='all'||record.branchId===branchId.value)&&(!status.value||record.status===status.value)&&(!search.value||JSON.stringify(record).toLowerCase().includes(search.value.toLowerCase()))))
const cards=computed(()=>{const all=filtered.value;return[{label:'Recognized expenses',value:all.reduce((sum,r)=>sum+Number(r.amount||0),0)},{label:'Outstanding payables',value:all.reduce((sum,r)=>sum+Number(r.outstandingAmount||0),0)},{label:'Payments made',value:all.reduce((sum,r)=>sum+Number(r.paidAmount||0),0)}]})
const api=async(path,body)=>{await auth.authStateReady?.();const token=await auth.currentUser?.getIdToken();if(!token)throw Error('Sign in to continue.');let last;for(const base of OTP_BACKEND_CANDIDATES){try{const response=await fetch(base+path,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok||!result.success)throw Error(result.error);return result.data}catch(e){last=e}}throw last||Error('Finance service is unavailable.')}
const load=async()=>{loading.value=true;try{const workspace=await api('/supply/workspace?branchId=all');branches.value=workspace.branches||[];permissions.value=workspace.permissions||[];records.value=await api('/finance/records?branchId=all');error.value=''}catch(e){error.value=e.message}finally{loading.value=false}}
const create=async()=>{saving.value=true;try{await api('/finance/expenses',draft.value);showForm.value=false;draft.value=blank();await load()}catch(e){error.value=e.message}finally{saving.value=false}}
const openPayment=record=>{paymentTarget.value=record;payment.value={amount:(Number(record.outstandingAmount||0)/100).toFixed(2),paymentMethod:'',paymentReference:''}}
const recordPayment=async()=>{saving.value=true;try{await api(`/finance/expenses/${paymentTarget.value.id}/payments`,payment.value);paymentTarget.value=null;await load()}catch(e){error.value=e.message}finally{saving.value=false}}
onMounted(load);watch(branches,()=>{if(!draft.value.branchId&&branches.value.length===1)draft.value.branchId=branches.value[0].id})
</script>

<style scoped>input,select,textarea{display:block;width:100%;margin-top:.3rem;border:1px solid #475569;border-radius:.5rem;background:#1e293b;padding:.55rem .7rem;color:#f8fafc}label{font-size:.82rem;color:#cbd5e1}button{border:1px solid #64748b;border-radius:.5rem;padding:.5rem .75rem;font-size:.84rem}th,td{padding:.8rem;vertical-align:top}th{font-size:.72rem}</style>
